rule logistic:
    input:
        multiext("plinkdata.", "fam", "map", "ped", "cov")
    output:
        "plinkdata.assoc.logistic"
    params:
        covar=True,
        extra_logistic="--parameters 1-5, 7",
        extra_covar="",
        covariables=["quantitative_column", "case_control_with_missingness"]
    threads: 1
    log:
        "logs/plink/logistic.log"
    wrapper:
        "master/bio/plink/logistic"
