rule toulligqc:
    input:
        "demodata/sequencing_summary.txt",
    output:
        "toulligqc_sequencing_summary/report.html",
    log:
        "merged.log",
    params:
        extra="",  # optional additional parameters as string
    wrapper:
        "master/bio/toulligqc"