rule rsem:
    input:
        # BAM file mapped against RSEM index (see manual)
        "mapped/{sample}.bam"
    output:
        "expressions/{sample}.rsem.genes.results"
    log:
        "logs/rsem/{sample}.log"
    params:
        # path to RSEM index (see manual)
        index="index/",
        # prefix for output files
        prefix="expressions/{sample}.rsem",
        # optional parameters (add --paired-end if alignmnents are paired-end)
        extra=""
    threads: 8
    wrapper:
        "master/bio/rsem/calculate-expression"
