rule razers3:
    input:
        reads=["reads/{sample}.1.fastq", "reads/{sample}.2.fastq"], # list of input reads
    output:
        "mapped/{sample}.bam", # output format is automatically inferred from file extension. Can be bam/sam or other formats.
    log:
        "logs/razers3/{sample}.log",
    params:
        genome="genome.fasta", # the reference genome
         # additional parameters
        extra="",
    threads: 8
    wrapper:
        "master/bio/razers3"
