rule model:
    input:
        multiext("plinkdata.", "fam", "map", "ped")
    output:
        multiext("plinkdata.", "model", "model.best.fisher.mperm")
    params:
        extra_model="fisher-midp mperm=5000 --hwe 1e-8 midp --seed 9034"
    threads: 1
    log:
        "logs/plink/model.log"
    wrapper:
        "master/bio/plink/model"
