name: "gbasf2"
description: Gbasf2 is a helper package to use the Belle II Computing Grid, similar to the LHC Computing Grid. To be run on KEKcc computing cluster. Takes care of proxy setup, job submission and steering, as well as log and output data download. Returns log files and text files with lists of paths of downloaded output files. Based on the b2luigi helper package for Luigi.
url: https://software.belle2.org/development/sphinx/online_book/computing/gbasf2.html
authors:
  - Caspar Schmitt
  - b2luigi authors (https://github.com/nils-braun/b2luigi)
output:
  - output_filelist: text file with list of downloaded output file paths [str]
  - proxy_text_file: test file generated by a separate rule with setProxy = True [str,optional]
params:
  - steeringfile: path to python steering file [str]
  - gbasf2_dataset: absolute path of gbasf2 input data set on grid [str]
  - gbasf2_output_file_name: file name of output files, ends with .root [str]
  - release: specify basf2 software release [str]
  - sandbox_input_files: list of additional sandbox file paths, relative to steering file path [list(str), optional]
  - maxretries: maximum number of tries for job rescheduling [int, optional]
  - gbasf2_download_logs: log files should or should not be downloaded [bool, optional]
  - basf2_min_proxy_lifetime: minimum live time for proxy when submitting [int, optional]
  - gbasf2_proxy_lifetime: live time of proxy for proxy setup [int, optional]
  - setProxy: for proxy setup only [bool, optional]
notes:
  - to make sure the proxy is initialized only once, use a separate rule with setProxy=True and require proxy_text_file in the subsequent rules.
