rule gatk_baserecalibratorspark:
    threads: 8
    input:
        bam="mapped/{sample}.bam",
        ref="genome.fasta",
        known="dbsnp.vcf.gz"  # optional known sites
    output:
        recal_table="recal/{sample}.grp"
    log:
        "logs/gatk/baserecalibrator/{sample}.log"
    params:
        extra="",  # optional
        java_opts="", # optional
        #spark_runner="",  # optional
        #spark_master="",  # optional
        #spark_extra="", # optional
    wrapper:
        "master/bio/gatk/baserecalibratorspark"
