rule cooltools_expected_trans:
    input:
        cooler="CN.mm9.1000kb.mcool", ## Multiresolution cooler file
    output:
        "{sample}_{resolution,[0-9]+}.trans.expected.tsv"
    params:
        ## Add optional parameters 
        view="mm9_view.txt", ## File with the chromosome names and lengths
    log:
        "logs/expected_trans/{sample}_{resolution}_trans_expected.log"
    wrapper:
        "master/bio/cooltools/expected_trans"
