rule diamond_blastp:
    input: 
        pep = "test.fa",
        db =  "test.dmnd"
    output:
        "test_dmnd.txt.gz"
    params:
        pval=".01",
        extra=""
    threads: 4
    resources:
        mem_mb=4000 # define amount of memory to be used by pear
    wrapper:
        "master/bio/diamond"
