rule jannovar:
    input:
        "{sample}.vcf",
    output:
        "jannovar/{sample}.vcf.gz"
    log:
        "logs/jannovar/{sample}.log"
    params:
        pedigree="pedigree_ar.ped", # optional, contains familial relationships
        database="hg19_small.ser",  # path to jannovar reference dataset
        extra="--show-all"          # optional parameters
    wrapper:
        "master/bio/jannovar"
