rule cooltools_eigs_trans:
    input:
        cooler="CN.mm9.1000kb.mcool", ## Multiresolution cooler file
    output:
        "CN_{resolution,[0-9]+}.trans.eigs.tsv"
    params:
        ## Add optional parameters 
    log:
        "logs/CN_{resolution}_trans_eigs.log"
    wrapper:
        "master/bio/cooltools/eigs_trans"
