rule cooltools_eigs_trans:
    input:
        cooler="CN.mm9.1000kb.mcool", ## Multiresolution cooler file
    output:
        "{sample}_{resolution,[0-9]+}.trans.eigs.tsv"
    params:
        ## Add optional parameters 
        view="mm9_view.txt", ## File with the chromosome names and lengths
    log:
        "logs/expected_cis/{sample}_{resolution}_trans_eigs.log"
    wrapper:
        "master/bio/cooltools/eigs_trans"
