rule cooltools_eigs_trans:
    input:
        cooler="CN.mm9.1000kb.mcool",  ## Multiresolution cooler file
    output:
        vecs="CN_{resolution,[0-9]+}.trans.vecs.tsv",
        lam="CN_{resolution,[0-9]+}.trans.lam.tsv",
        bigwig="CN_{resolution,[0-9]+}.trans.bw",
    params:
        ## Add optional parameters
        extra="",
    log:
        "logs/CN_{resolution}_trans_eigs.log",
    wrapper:
        "master/bio/cooltools/eigs_trans"
