rule bowtie2_paired:
    input:
        read1=["reads/{sample}.1.fastq"],
        read2=["reads/{sample}.2.fastq"],
        index="index/genome.1.bt2"# the <prefix>.1.bt2 index file built with bowtie2-build
    output:
        "mapped/{sample}_pe.bam"
    log:
        "logs/bowtie2/{sample}_pe.log"
    params:
        extra=""  # optional parameters
    threads: 4
    wrapper:
        "master/bio/bowtie2/align"

rule bowtie2_single:
    input:
        single=["reads/{sample}.1.fastq", "reads/{sample}.2.fastq"],
        index="index/genome.1.bt2"# the <prefix>.1.bt2 index file built with bowtie2-build
    output:
        "mapped/{sample}_se.bam"
    log:
        "logs/bowtie2/{sample}_se.log"
    params:
        extra=""  # optional parameters
    threads: 4
    wrapper:
        "master/bio/bowtie2/align"
