rule bowtie2:
    input:
        ref="genome.fasta",
        sample=["reads/{sample}.1.fastq", "reads/{sample}.2.fastq"]
    output:
        "mapped/{sample}.bam"
    log:
        "logs/bowtie2/{sample}.log"
    params:
        ""  # optional parameters
    threads: 8
    wrapper:
        "master/bio/bowtie2/align"
