rule gatk_estimate_library_complexity:
    input:
        bam="{sample}.bam",
    output:
        metrics="{sample}.metrics",
    log:
        "logs/{sample}.log",
    params:
        extra="",
        java_opts="",  # optional
    resources:
        mem_mb=1024,
    wrapper:
        "master/bio/gatk/estimatelibrarycomplexity"
