rule define_columns:
    input:
        "ntuple0.root",
    output:
        "ntuple0_output.root",
    log:
        "logs/define_columns/define_columns.log",
    params:
        input_tree_name="TestTree",
        output_tree_name="TestTree",
        branches=[
            ["p2", "px * px + py * py + pz * pz"],
            ["pt", "sqrt(px * px + py * py)"],
        ],
        redefine=["pt"],
    threads: 2
    wrapper:
        "master/phys/root/define_columns"
