rule optitype:
    input:
        # list of input reads
        reads=["reads/{sample}_1.fished.fastq", "reads/{sample}_2.fished.fastq"]
        #config="config_file",
    output:
        pdf="optitype/{sample}_coverage_plot.pdf",
        tsv="optitype/{sample}_result.tsv",
    log:
        "logs/optitype/{sample}.log"
    params:
        sequencing_type="dna",
        extra="",
    wrapper:
        "master/bio/optitype"
