rule optitype:
    input:
        reads=["reads/{sample}_1.fished.fastq", "reads/{sample}_2.fished.fastq"], # list of input reads
    output:
        multiext("optitype/{sample}", "_coverage_plot.pdf", "_result.tsv"),
    log:
        "logs/optitype/{sample}.log",
    params:
        sequencing_type="dna", # Type of sequencing data. Can be 'dna' or 'rna'. Default is 'dna'.
         # optiype config file, optional
        config="", # additional parameters
        extra="",
    wrapper:
        "master/bio/optitype"
