
rule adapterremoval_se:
    input:
        sample=["reads/se/{sample}.fastq"],
    output:
        fq="trimmed/se/{sample}.fastq.gz",  # trimmed reads
        discarded="trimmed/se/{sample}.discarded.fastq.gz",  # reads that did not pass filters
        json="stats/se/{sample}.json",  # parameters as well as overall statistics
    log:
        "logs/adapterremoval/se/{sample}.log",
    threads: 1
    params:
        adapters="--adapter1 ACGGCTAGCTA",
        extra="",
    wrapper:
        "master/bio/adapterremoval"


rule adapterremoval_pe:
    input:
        sample=["reads/pe/{sample}.1.fastq", "reads/pe/{sample}.2.fastq"],
    output:
        fq1="trimmed/pe/{sample}_R1.fastq.gz",  # trimmed mate1 reads
        fq2="trimmed/pe/{sample}_R2.fastq.gz",  # trimmed mate2 reads
        merged="trimmed/pe/{sample}.merged.fastq.gz",  # overlapping mate-pairs which have been merged into a single read
        singleton="trimmed/pe/{sample}.singleton.fastq.gz",  # mate-pairs for which the mate has been discarded
        discarded="trimmed/pe/{sample}.discarded.fastq.gz",  # reads that did not pass filters
        html="stats/pe/{sample}.html",  # parameters as well as overall statistics
    log:
        "logs/adapterremoval/pe/{sample}.log",
    threads: 2
    params:
        adapters="--adapter1 ACGGCTAGCTA --adapter2 AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC",
        extra="--merge",
    wrapper:
        "master/bio/adapterremoval"
