rule test_pcaexplorer_pcaplot:
    input:
        "dst.RDS",
    output:
        png="pca.png",
        pdf="pca.pdf",
        svg="pca.svg",
    params:
        extra="",
    log:
        "logs/pca.log",
    wrapper:
        "master/bio/pcaexplorer/pcaplot"
