rule test_pcaexplorer_pcaplot:
    input:
        "dst.RDS",
    output:
        "pca.svg",
    params:
        extra="",
    log:
        "logs/pca.log",
    wrapper:
        "master/bio/pcaexplorer/pcaplot"
