rule strelka:
    input:
        tumor="data/{tumor}.bam", # The normal bam and its index
         # are optional input
         # normal = "data/b.bam",
         # normal_index = "data/b.bam.bai"
        tumor_index="data/{tumor}.bam.bai",
        fasta="data/genome.fasta",
        fasta_index="data/genome.fasta.fai",
    output:
        directory("{tumor}_vcf"), # Strelka output - can be directory or full file path
    threads: 1
    params:
        run_extra="",
        config_extra="",
    log:
        "logs/strelka_{tumor}.log",
    wrapper:
        "master/bio/strelka/somatic"
