rule disambiguate:
    input:
        a="mapped/{sample}.a.bam",
        b="mapped/{sample}.b.bam"
    output:
        "disambiguate/{sample}.ambiguousSpeciesA.bam",
        "disambiguate/{sample}.ambiguousSpeciesB.bam",
        "disambiguate/{sample}.disambiguatedSpeciesA.bam",
        "disambiguate/{sample}.disambiguatedSpeciesB.bam"
    params:
        algorithm="bwa",
        extra=""
    wrapper:
        "master/bio/ngs-disambiguate"
