rule samtools_collate:
    input:
        "mapped/{sample}.bam",
    output:
        "mapped/{sample}.collated.bam",
    log:
        "{sample}.log",
    params:
        extra="-f",
    threads: 2
    wrapper:
        "master/bio/samtools/collate"
