rule bowtie2_index:
    input:
        "genome.fasta" 
    output:
        donefile = "bt2_index/genome.bowtie2index.done"
    log:
        "logs/bt2index_genome.log"
    params:
        index="bt2_index/genome",  # prefix of reference genome index (built with bowtie2-build)
        extra=""  # optional parameters
    threads: 8
    wrapper:
        "master/bio/bowtie2/index"
