rule test_rseqc_inner_distance:
    input:
        aln="A.bam",
        refgene="annotation.bed",
    output:
        reads_inner_distance="a.txt",
        freq="freq.txt",
        pdf="a.pdf",
        plot_r="script.a.r",
    log:
        "rseqc.log",
    params:
        extra="-k3 -q2",
    wrapper:
        "master/bio/rseqc/inner_distance"
