rule gatk_printreadsspark:
    input:
        bam="mapped/{sample}.bam",
        ref="genome.fasta",
        dict="genome.dict",
    output:
        bam="{sample}.bam",
    log:
        "logs/{sample}.log",
    params:
        extra="",  # optional
        java_opts="",  # optional
        #spark_runner="",  # optional, local by default
        #spark_master="",  # optional
        #spark_extra="", # optional
    resources:
        mem_mb=1024,
    threads: 8
    wrapper:
        "master/bio/gatk/printreadsspark"
