rule test_nonpareil_plot:
    input:
        npo="{sample}.npo",
    output:
        pdf="results/{sample}.pdf",
    threads: 1
    log:
        "logs/{sample}.log",
    params:
        label="Plot",
        col="blue",
        enforce_consistency=True,
        star=95,
        correction_factor=True,
        weights_exp="-1.1,-1.2,-0.9,-1.3,-1",
        skip_model=False,
    wrapper:
        "master/bio/nonpareil/plot"
