rule test_nonpareil_plot:
    input:
        npo="{sample}.npo",
    output:
        pdf="results/{sample}.pdf",
        tsv="results/{sample}.tsv",
        json="results/{sample}.json",
    threads: 1
    log:
        "logs/{sample}.log",
    params:
        extra=lambda w: f"--labels {w.sample} --col blue",
    wrapper:
        "master/bio/nonpareil/plot"


use rule test_nonpareil_plot as test_nonpareil_plot_multiple with:
    input:
        npo=["a.npo", "b.npo", "c.npo"],
    output:
        pdf="results/samples.pdf",
        tsv="results/samples.tsv",
        json="results/samples.json",
    log:
        "logs/samples.log",
    params:
        extra="--labels 'Model A,Model B,Model C' --col blue,red,green",


use rule test_nonpareil_plot as test_nonpareil_plot_nomodel with:
    output:
        pdf="results/{sample}.nomodel.pdf",
        tsv="results/{sample}.nomodel.tsv",
        json="results/{sample}.nomodel.json",
    log:
        "logs/{sample}.nomodel.log",
    params:
        extra=lambda w: f"--labels {w.sample} --col blue --no-model",
