rule whatshap_haplotag:
    input:
        vcf="haplotag.10X.vcf.gz",
        aln="haplotag.10X.bam",
        "haplotag.10X.vcf.gz.tbi",
        "haplotag.10X.bam.bai", 
        ref = "reference.fasta",
        "reference.fasta.fai"
    output:
        "haplotag.10X.phased.bam"
    params:
        extra="" # optionally use --ignore-linked-read, --tag-supplementary, etc.
    log:
        "logs/haplotag.10X.phased.log"
    threads: 4
    wrapper:
        "master/bio/whatshap/haplotag"
