rule whatshap_haplotag:
    input:
        vcf="haplotag.10x.vcf.gz",
        tbi="haplotag.10x.vcf.gz.tbi",
        bam="haplotag.10x.bam",
        bai="haplotag.10x.bam.bai",
        reference = "reference.fasta"
    output:
        "haplotag.10X.phased.bam"
    params:
        extra="" # optionally use --ignore-linked-read 
    log:
        "logs/haplotag.10X.phased.log"
    threads: 4
    wrapper:
        "master/bio/whatshap/haplotag"
