rule orthanq_candidates_virus:
    input:
        genome="genome.fasta",
        genome_fai="genome.fasta.fai",
        lineages="lineages.fasta"
    output:
        candidates = "candidates.vcf",
    log:
        "logs/orthanq_candidates/candidates_virus.log",
    wrapper:
        "master/bio/orthanq/virus/candidates"
