rule gatk_clean_sam:
    input:
        bam="{sample}.bam"
    output:
        clean="{sample}.clean.bam"
    log:
        "logs/{sample}.log"
    params:
        extra="",
	java_opts="", # optional
    resources:
        mem_mb=1024,
    wrapper:
        "master/bio/gatk/cleansam"
