rule test_deeptools_alignment_sieve:
    input:
        aln="a.bam",
    output:
        "res.bam",
    threads: 1
    log:
        "logs/deeptools.log"
    params:
        extra=""
    wrapper:
        "master/bio/deeptools/alignmentsieve"
