rule primerclip:
    input:
        master_file="master_file",
        alignment_file="mapped/{sample}.bam"
    output:
        #Not for now it only possible to get output as a sam-file
        alignment_file="mapped/{sample}.trimmed.bam"
    log:
        "logs/primerclip/{sample}.log"
    params:
        extra=""
    wrapper:
        "master/bio/primerclip"
