__author__ = "Christopher Schröder, Patrik Smeds"
__copyright__ = "Copyright 2020, Christopher Schröder, Patrik Smeds"
__email__ = "christopher.schroeder@tu-dortmund.de, patrik.smeds@gmail.com"
__license__ = "MIT"

from os import path

from snakemake.shell import shell

log = snakemake.log_fmt_shell(stdout=False, stderr=True)

# Check inputs/arguments.
if len(snakemake.input) == 0:
    raise ValueError("A reference genome has to be provided.")
elif len(snakemake.input) > 1:
    raise ValueError("Please provide exactly one reference genome as input.")

valid_suffixes = [".0123", ".amb", ".ann", ".bwt.2bit.64", ".pac"]
prefixes = []
for s in snakemake.output:
    if s.endswith(".bwt.2bit.64"):
        suffix = ".bwt.2bit.64"
    else:
        suffix = s[:-4]
    if not suffix in valid_suffixes:
        raise ValueError(f"{s} cannot be generated by bwa-mem2 index (invalid suffix).")
    prefixes.append(s[:-len(suffix)])

if len(set(prefixes)) != 1:
    raise ValueError("Output files must share common prefix up to their file endings.")
prefix = prefixes[0]

shell(f"bwa-mem2 index -p {prefix} {snakemake.input[0]} {log}")
