########################################################
# Snakefile for pytrf wrapper
########################################################


include: "extra_rules.smk"  # [hide]


# SAMPLE RULE: Custom parameters via extra
rule pytrf_findstr:
    input:
        seq="demo_data/{sample}.fasta",
    output:
        "results/{sample}_findstr.csv",
    params:
        subcommand="findstr",
        extra="-r 5 1 3 3 3 3",
    log:
        "logs/{sample}.log",
    wrapper:
        "master/bio/pytrf"


# SAMPLE RULE: Minimal usage with defaults
rule pytrf_findstr_defaults:
    input:
        seq="demo_data/small_test.fasta",
    output:
        "results/small_test_findstr_defaults.tsv",
    params:
        subcommand="findstr",
    log:
        "logs/small_test_defaults.log",
    wrapper:
        "master/bio/pytrf"
