rule test_snpsift_annotate:
    input:
        vcf = "in.vcf",
        database = "annotation.vcf"
    output:
        out = "out.vcf"
    message:
        "Testing SnpSift Annotate"
    log:
        "annotate.log"
    wrapper:
        "master/bio/snpfit/annotate"
