rule arriba:
    input:
        bam="{sample}.bam", # STAR bam containing chimeric alignments
         # path to reference genome
        genome="genome.fasta", # path to annotation gtf
        annotation="annotation.gtf",
    output:
        fusions="fusions/{sample}.tsv", # approved gene fusions
         # discarded gene fusions
        discarded="fusions/{sample}.discarded.tsv", # optional
    log:
        "logs/arriba/{sample}.log",
    params:
        blacklist="blacklist.tsv", # arriba blacklist file
         # strongly recommended, see https://arriba.readthedocs.io/en/latest/input-files/#blacklist
         # file containing known fusions
        known_fusions="", # optional
         # file containing information from structural variant analysis
        sv_file="", # optional
         # optional parameters
        extra="-T -P -i 1,2",
    threads: 1
    wrapper:
        "master/bio/arriba"
