pindel_types = ["D", "BP", "INV", "TD", "LI", "SI", "RP"]


rule pindel:
    input:
        ref="genome.fasta",
        # samples to call
        samples=["mapped/a.bam"],
        # bam configuration file, see http://gmt.genome.wustl.edu/packages/pindel/quick-start.html
        config="pindel_config.txt",
    output:
        expand("pindel/all_{type}", type=pindel_types),
    params:
        extra="",  # optional parameters (except -i, -f, -o, -j, -J)
    log:
        "logs/pindel.log",
    threads: 4
    wrapper:
        "master/bio/pindel/call"


rule pindel_include_regions:
    input:
        ref="genome.fasta",
        samples=["mapped/a.bam"],
        config="pindel_config.txt",
        include_bed="regions.bed",
    output:
        expand("pindel/all_included_{type}", type=pindel_types),
    log:
        "logs/pindel_j.log",
    threads: 4
    wrapper:
        "master/bio/pindel/call"


rule pindel_exclude_regions:
    input:
        ref="genome.fasta",
        samples=["mapped/a.bam"],
        config="pindel_config.txt",
        exclude_bed="regions.bed",
    output:
        expand("pindel/all_excluded_{type}", type=pindel_types),
    log:
        "logs/pindel_include.log",
    threads: 4
    wrapper:
        "master/bio/pindel/call"
