rule bed_to_interval_list:
    input:
        bed="rescources/{region}.bed",
        dict="rescources/genome.dict"
    output:
        "{region}.interval_list"
    log:
        "logs/picard/bedtointervallist/{region}.log"
    params:
        # optional parameters
        "SORT=true " # sort output interval list before writing
    wrapper:
        "master/bio/picard/bedtointervallist"

