rule dada2_remove_chimeras:
    input:
        "results/dada2/seqTab.RDS" # Sequence table
    output:
        "results/dada2/seqTab.nochim.RDS" # Chimera-free sequence table
    params: {} # Additional arguments can be provided here
    log:
        "logs/dada2/remove-chimeras/remove-chimeras.log"
    threads: 1 # set desired number of threads here
    wrapper:
        "master/bio/dada2/remove-chimeras"
