rule mpileup_to_vcf:
    input:
        "mpileup/{sample}.mpileup.gz"
    output:
        "vcf/{sample}.vcf"
    message:
        "Calling SNP with Varscan2"
    threads:  # Varscan does not take threadding information
        1     # However, mpileup must be gunzipped. Keep threading value to
              # one for unzipped mpileup input, or set it to two, and the
              # wrapper will unzip your mpileup on the fly.
    wrapper:
        "https://bitbucket.org/tdayris/snakemake-wrappers/raw/varscan2/bio/varscan/mpileup2snp"
