rule bwa_mem:
    input:
        ref="genome.fasta",
        sample=["reads/{sample}.1.fastq", "reads/{sample}.2.fastq"]
    output:
        "mapped/{sample}.bam"
    log:
        "logs/bwa_mem/{sample}.log"
    params:
        bwa_extra=r"-R '@RG\tID:{sample}\tSM:{sample}'",
        sort_extra="-n"
    threads: 8
    wrapper:
        "master/bio/bwa/mem-sorted"
