from snakemake.utils import min_version

min_version("9.13.1")

configfile: "config.yaml"

module calc_consensus_reads:
    snakefile: "../meta_wrapper.smk"
    config: config

use rule * from calc_consensus_reads