rule jackhmmer:
    input:
        db="test-protein.fa",
        query="query.fa"
    output:
        # Each of the following outputs is optional, and are described below as an example.
        tblout="test-prot-tbl.txt", # save parseable table of per-sequence hits to file <f>
        domtblout="test-prot-domtbl.txt", # save parseable table of per-domain hits to file <f>
        alignment_hits="test-prot-alignment-hits.sto", # Save a multiple alignment of all significant hits (those satisfying inclusion thresholds) to the file <f>
        outfile="test-prot-out1.txt", # Direct the main human-readable output to a file <f> instead of the default stdout. 
    log:
        "logs/jackhmmer.log"
    params:
       # Additional flags can be set using extra, for example:
       extra="-E 0.001 --F1=0.005"
    threads: 4
    wrapper:
        "master/bio/hmmer/jackhmmer"
