rule plot_profile:
    input:
        "matrix.gz", # matrix file from deepTools computeMatrix tool
    output:
        plot_img="plot_profile/plot.png", # Please note that --outFileSortedRegions and --outFileNameData are exclusively defined via output files.
         # Usable output variables, their extensions and which option they implicitly call are listed here:
         #         https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/deeptools/plotprofile.html.
         # Through the output variables image file and more output options for plot profile can be selected.
         # required
         # optional output files
        regions="plot_profile/regions.bed",
        data="plot_profile/data.tab",
    log:
        "logs/deeptools/plot_profile.log",
    params:
        "--plotType=fill "
        "--perGroup "
        "--colors red yellow blue "
        "--dpi 150 ", # optional parameters
    wrapper:
        "master/bio/deeptools/plotprofile"
