rule test_gatk_get_pileup_summaries:
    input:
        bam="mapped/a.bam",
        intervals="genome/intervals.bed",
        variants="genome/variants.vcf.gz",
    output:
        "summaries.table",
    threads: 1
    resources:
        mem_mb=1024,
    params:
        extra="",
    log:
        "logs/summary.log",
    wrapper:
        "master/bio/gatk/getpileupsummaries"
