rule bazam_interleaved:
    input:
        bam="mapped/{sample}.bam",
    output:
        reads="results/reads/{sample}.fastq",
    log:
        "logs/bazam/{sample}.log",
    wrapper:
        "master/bio/bazam"


rule bazam_separated:
    input:
    output:
        r1="results/reads/{sample}.r1.fastq",
        r2="results/reads/{sample}.r2.fastq",
    log:
        "logs/bazam/{sample}.log",
    wrapper:
        "master/bio/bazam"
