rule dada2_dereplicate_fastq:
    input:
        "filtered/{fastq}.fastq", # Quality filtered FASTQ file
    output:
        "uniques/{fastq}.RDS", # Dereplicated sequences stored as `derep-class` object in a RDS file 
    log:
        "logs/dada2/dereplicate-fastq/{fastq}.log",
    wrapper:
        "master/bio/dada2/dereplicate-fastq"
