rule samtools_depth:
    input:
        bams = ["mapped/A.bam", "mapped/B.bam"],
    output:
        "depth.txt"
    params:
        # optional bed file passed to -b
        bed = "regionToCalcDepth.bed",
        extra = "" # optional additional parameters as string
    wrapper:
        "master/bio/samtools/depth"
