rule preprocess_variants:
    input:
        variants="variants.vcf", ##vcf/bcf
    output:
        "normalized/variants.vcf",
    params:
        genome="genome.fasta", ## path to reference genome
         ## parameters such as -L to left-align variants
        extra="-L",
    threads: 2
    wrapper:
        "master/bio/hap.py/pre.py"
