rule dada2_assign_species:
    input:
        seqs="results/dada2/seqTab.nochim.RDS", # Chimera-free sequence table
        refFasta="resources/species.fasta" # Reference FASTA for Genus-Species taxonomy
    output:
        "results/dada2/genus-species-taxa.RDS" # Genus-Species taxonomic assignments
    # Even though this is an R wrapper, use named arguments in Python syntax
    # here, to specify extra parameters. Python booleans (`arg1=True`, `arg2=False`)
    # and lists (`list_arg=[]`) are automatically converted to R.
    # For a named list as an extra named argument, use a python dict
    #   (`named_list={name1=arg1}`).
    #params:
    #    allowMultiple=True
    log:
        "logs/dada2/assign-species/assign-species.log"
    threads: 1 # set desired number of threads here
    wrapper:
        "master/bio/dada2/assign-species"
