rule varscan_somatic_single_mpileup:
    input:
        "mpileup/{sample}.mpileup.gz",
    output:
        snp="single_mpileup/vcf/{sample}.snp.vcf",
        indel="single_mpileup/vcf/{sample}.indel.vcf",
    log:
        "logs/single_mpileup/{sample}.log",
    message:
        "Calling somatic variants from sample {wildcards.sample} using a normal-tumor file"
    threads: 1
    resources:
        mem_mb=1024,
    params:
        extra="",
    wrapper:
        "master/bio/varscan/somatic"


rule varscan_somatic_dual_mpileup:
    input:
        "mpileup/{sample}.mpileup.gz",
        "mpileup/{sample}.tumor.mpileup.gz",
    output:
        snp="dual_mpileup/vcf/{sample}.snp.vcf",
        indel="dual_mpileup/vcf/{sample}.indel.vcf",
    log:
        "logs/dual_mpileup/{sample}.log",
    message:
        "Calling somatic variants from sample {wildcards.sample} using both normal and tumor files."
    threads: 1
    resources:
        mem_mb=1024,
    params:
        extra="",
    wrapper:
        "master/bio/varscan/somatic"
