rule varscan_somatic:
    input:
        # A pair of pileup files can be used *instead* of the mpileup
        "mpileup/{sample}.mpileup.gz"
        #"mpileup/{sample}.tumor.mpileup.gz"
    output:
        snp = "vcf/{sample}.snp.vcf",
        indel = "vcf/{sample}.indel.vcf"
    message:
        "Calling somatic variants {wildcards.sample}"
    threads:
        1
    resources:
        mem_mb=1024
    params:
        extra = ""
    wrapper:
        "master/bio/varscan/somatic"
