rule gatk_applybsqr:
    input:
        bam="mapped/{sample}.bam",
        ref="genome.fasta",
        recal_table="recal/{sample}.grp"
    output:
        bam="recal/{sample}.bam"
    log:
        "logs/gatk/gatk_applybsqr/{sample}.log"
    params:
        extra="",  # optional
        java_opts="", # optional
    wrapper:
        "master/bio/gatk/applybsqr"
