
rule run_spades:
    input:
        reads=["test_reads/sample1_R1.fastq.gz","test_reads/ample1_R2.fastq.gz"]
    output:
        # Don't put output in shadow directory, other output, necessary for restart are created
        "assembly/contigs.fasta",
        "assembly/scaffolds.fasta",
    benchmark:
        "logs/benchmarks/assembly/spades.txt"
    params:
        k= 'auto',
        extra = "--only-assembler"
    log:
        "log/spades.log",  #stdout/stderr is written in first log file
        "assembly/spades.log",  #spades creates anyway a this log file
    threads: 8
    resources:
        mem_mem=250e3,
        time=60 * 24,
    wrapper:
        "master/bio/bwa/aln"


rule download_reads:
    output:
        ["test_reads/sample1_R1.fastq.gz","test_reads/ample1_R2.fastq.gz"]
    shell:
        " wget https://zenodo.org/record/3992790/files/test_reads.tar.gz "
        " tar -xzf test_reads.tar.gz "
