rule dada2_add_species:
    input:
        taxtab="results/dada2/taxa.RDS", # Taxonomic assignments
        refFasta="resources/example_species_assignment.fa.gz" # Reference FASTA 
    output:
        "results/dada2/taxa-sp.RDS", # Taxonomic + Species assignments
    # Even though this is an R wrapper, use named arguments in Python syntax
    # here, to specify extra parameters. Python booleans (`arg1=True`, `arg2=False`)
    # and lists (`list_arg=[]`) are automatically converted to R.
    # For a named list as an extra named argument, use a python dict
    #   (`named_list={name1=arg1}`).
    #params:
    #    verbose=True
    log:
        "logs/dada2/add-species/add-species.log"
    threads: 1 # set desired number of threads here
    wrapper:
        "master/bio/dada2/add-species"
