rule mofa2_plotting:
    input:
        "{data}.hdf5",
    output:
        overview="results/{data}_overview.png",
        # variance_explained="results/{data}_variance_explained.png",
        # feature_weights="results/{data}_feature_weights.png",
        # data_heatmap="results/{data}_data_heatmap.png",
        # data_scatter="results/{data}_data_scatter.png",
    log:
        "log/{data}.log",
    # params:
    wrapper:
        "master/bio/mofa2"
