rule realignertargetcreator:
    input:
        bam="mapped/{sample}.bam"
        ref="genome.fasta",
        known="dbsnp.vcf.gz"
    output:
        "{sample}.intervals"
    log:
        "logs/gatk/realignertargetcreator/{sample}.log"
    params:
        extra="",  # optional
    resources:
        mem_mb = 1024
    threads: 16
    wrapper:
        "bio/gatk3/realignertargetcreator"
