rule strelka_germline:
    input:
        bam="mapped/{sample}.bam", # the required bam file
         # path to reference genome fasta and index
        fasta="genome.fasta",
        fasta_index="genome.fasta.fai",
    output:
        directory("strelka/{sample}"), # Strelka results - either use directory or complete file path
    log:
        "logs/strelka/germline/{sample}.log",
    params:
        config_extra="", # optional parameters
        run_extra="",
    threads: 8
    wrapper:
        "master/bio/strelka/germline"
