name: MaGeCK FluteMLE
description: |
  CRISPR integrative analysis pipeline using the gene summary table in 
  MAGeCK MLE results
url: https://bioconductor.org/packages/3.20/bioc/html/MAGeCKFlute.html
authors:
  - Thibault Dayris
input:
  - Path to the MLE gene summary table
output:
  - Path to the directory holding results
params:
  Any named argument present in MAGeCKFlute:FluteMLE function (see URL above).
  Remember `treatname` **MUST** be included, while `gene_summary` and `outdir`
  are automatically determined from IO and therefore must **not** be included.
notes: |
  The output directory content depends on optional parameters and the content of the
  CRISPR data.
