rule all_test:
    input:
        "test_db/library/added/added.md5",


rule kraken2_add_to_library:
    input:
        fasta=lambda wc: [
            f"{wc.db}/library/tiny.fa",
            f"{wc.db}/library/tiny2.fa",
        ],
    output:
        "{db}/library/added/added.md5",
    params:
        db=lambda wc, output: output[0].split("/library/")[0],
        extra="",
    log:
        "{db}/library/added/added.log",
    wrapper:
        "master/bio/kraken2/add_to_library"
