
rule test_pyroe_makesplicedunspliced:
    input:
        fasta="genome.fasta",
        gtf="annotation.gtf",
        spliced="extra_spliced.fasta",  # Optional path to additional spliced sequences (FASTA)
        unspliced="extra_unspliced.fasta",  # Optional path to additional unspliced sequences (FASTA)
    output:
        gene_id_to_name="gene_id_to_name.tsv",
        fasta="spliceu.fa",
        g2g="spliceu_g2g.tsv",
        t2g_3col="spliceu_t2g_3col.tsv",
        t2g="spliceu_t2g.tsv",
    threads: 1
    log:
        "logs/pyroe.log",
    params:
        extra="",  # Optional parameters
    wrapper:
        "master/bio/pyroe/makeunspliceunspliced/"
