rule alignment_summary:
    input:
        bam = "mapped/a.bam",
        refflat = "annotation.refFlat"
    output:
        "results/a.rnaseq_metrics.txt"
    log:
        "logs/picard/rnaseq-metrics/a.log"
    # optional specification of memory usage of the JVM that snakemake will respect with global
    # resource restrictions (https://snakemake.readthedocs.io/en/latest/snakefiles/rules.html#resources)
    # and which can be used to request RAM during cluster job submission as `{resources.mem_mb}`:
    # https://snakemake.readthedocs.io/en/latest/executing/cluster.html#job-properties
    resources:
        mem_mb=1024
    wrapper:
        "master/bio/picard/collectrnaseqmetrics"
