rule alignment_summary:
    input:
        # BAM aligned, splicing-aware, to reference genome
        bam="mapped/a.bam",
	# Reference genome
        #ref="ref.fasta",
        # Annotation file containing transcript, gene, and exon data
        refflat="annotation.refFlat",
    output:
        "results/a.rnaseq_metrics.txt",
    params:
        # strand is optional (defaults to NONE) and pertains to the library preparation
        # options are FIRST_READ_TRANSCRIPTION_STRAND, SECOND_READ_TRANSCRIPTION_STRAND, and NONE
        strand="NONE",
        # optional additional parameters, for example,
        extra="--VALIDATION_STRINGENCY STRICT",
    log:
        "logs/picard/rnaseq-metrics/a.log",
    resources:
        mem_mb=1024,
    wrapper:
        "master/bio/picard/collectrnaseqmetrics"
