rule get_variation:
    output:
        vcf="refs/variation.vcf.gz"
    params:
        species="mus_musculus",
        release="98",
        type="structural_variations" # one of "all", "somatic", "structural_variation"
    log:
        "logs/get_variation.log"
    wrapper:
        "master/bio/reference/ensembl-variation"
