rule norm_vcf:
    input:
        "{prefix}.bcf",
    output:
        "{prefix}.norm.vcf",
    log:
        "{prefix}.norm.log",
    params:
        extra="--rm-dup none",  # optional
    wrapper:
        "master/bio/bcftools/norm"
