rule norm_vcf:
    input:
        "{prefix}.vcf",
    output:
        "{prefix}.vcf",
    log:
        "logs/bcftools-norm/{prefix}.log",
    params:
        "",  # optional parameters for bcftools norm (except -o)
    wrapper:
        "master/bio/bcftools/norm"
