rule obtain_asset:
    output:
        # the name refers to the refgenie seek key (see attributes on http://refgenomes.databio.org)
        fai="refs/genome.fasta"
        # Multiple outputs/seek keys are possible here.
    params:
        genome="human_alu",
        asset="fasta",
        tag="default"
    wrapper:
        "master/bio/refgenie"

rule obtain_large_asset:
    output:
        # the name refers to the refgenie seek key (see attributes on http://refgenomes.databio.org)
        star_index=directory("refs/star_index/hg38/star_index")
        # Multiple outputs/seek keys are possible here.
    params:
        genome="hg38",
        asset="star_index",
        tag="default"
    wrapper:
        "master/bio/refgenie"
