rule obtain_asset:
    output:
        fai="refs/genome.fasta", # the name refers to the refgenie seek key (see attributes on http://refgenomes.databio.org)
         # Multiple outputs/seek keys are possible here.
    params:
        genome="human_alu",
        asset="fasta",
        tag="default",
    wrapper:
        "master/bio/refgenie"
