rule get_fastq_pe:
    output:
        # the wildcard name must be accession, pointing to an SRA number
        "data/{accession}_1.fastq",
        "data/{accession}_2.fastq",
	temp = temp(directory("temp/{accession}_tmp")),
    log:
        "logs/{accession}_PE.log"
    params:
        extra="-v -v"
    threads: 6  # defaults to 6
    wrapper:
        "master/bio/sra-tools/fasterq-dump"


rule get_fastq_se:
    output:
        "data/{accession}.fastq.gz"
    log:
        "logs/{accession}.SE.log"
    params:
        extra="-v -v"
    threads: 6
    wrapper:
        "master/bio/sra-tools/fasterq-dump"
