name: cin-signature-quantification
description: |
  Quantification of copy number signatures in cancer samples from 
  copy number profiles. The signatures are a readout of mutational 
  processes resulting in chromosomal instability (CIN). Methods from 
  Drews et al. (Nature, 2022) and Macintyre et al. (Nature Genetics, 2018) are included.
url: https://github.com/markowetzlab/CINSignatureQuantification/
authors:
  - Simon Sack
input:
  - |
    A parquet file containing the samples with the following headers: `chromosome`, `start`, `end`, `segVal`, `sample`
output:
  - >
    `cnobj`: R-object containing all test results.
  - >
    `features`: Parquet file with a table of the feature distribution of each sample.
  - >
    `sample_by_component`: Parquet file with the samples by component.
  - >
    `signature_activities`: Parquet file with the sample by signature activities.
  - >
    `clinical_predictors`: Parquet file with a prediction whether a given sample is resistent or sensitive.
params:
  - >
    `experiment_name`: The name of the experiment.
