rule cooltools_saddle:
    input:
        cooler="CN.mm9.1000kb.mcool", ## Multiresolution cooler file
        track="CN_1000000.eigs.tsv", ## Track file
        expected="CN_1000000.cis.expected.tsv", ## Expected file
    output:
        "CN_{resolution,[0-9]+}.saddledump.npz"
    params:
        ## Add optional parameters 
        view="mm9_view.txt", ## File with the chromosome names and lengths
        range="--qrange 0.01 0.99"
    log:
        "logs/saddle/CN_{resolution}_saddle.log"
    wrapper:
        # "master/bio/cooltools/saddle"
        "file:/Users/ilya/Projects/snakemake-wrappers/bio/cooltools/saddle/"

# Note that in this test files are edited to remove 