rule extract_single_file:
    input:
        "test.7z",
    output:
        "results/7z/a.txt",
    log:
        "logs/libarchive/extract/extract_single_file.log",
    threads: 1
    params:
        internal_paths="textfile_a.txt",
    wrapper:
        "master/utils/libarchive/extract"


rule extract_multiple_files:
    input:
        "test.zip",
    output:
        ["results/zip/a.txt", "results/zip/b.txt"],
    log:
        "logs/libarchive/extract/extract_multiple_files.log",
    threads: 1
    params:
        internal_paths=["textfile_a.txt", "subfolder/textfile_b.txt"],
    wrapper:
        "master/utils/libarchive/extract"
