rule vcf_spec_validation:
    input:
        vcf="sample.vcf",
    output:
        "results/sample_VALID.vcf",
    log:
        "results/sample_VALID.log",
    params:
        R="genome.fasta",
    resources:
        mem_mb=1024,
    wrapper:
        "master/bio/gatk/validatevariants"
