rule cooltools_eigs_cis:
    input:
        cooler="CN.mm9.1000kb.mcool", ## Multiresolution cooler file
    output:
        "CN_{resolution,[0-9]+}.cis.eigs.tsv"
    params:
        ## Add optional parameters 
        view="mm9_view.txt", ## File with the chromosome names and lengths
    log:
        "logs/CN_{resolution}_cis_eigs.log"
    wrapper:
        "master/bio/cooltools/eigs_cis"
