name: porechop_abi
description: |
  Adapter trimming for Oxford Nanopore reads with optional ab initio adapter inference.
url: https://github.com/bonsai-team/Porechop_ABI
authors:
  - Artur Gomes
input:
  - fq: one FASTA/FASTQ read file (can be gzipped)
  - ab_initio_config: custom ab initio config file (optional)
  - custom_adapters: custom adapters file (optional)
output:
  - fq: one trimmed FASTA/FASTQ read file
  - consensus: consensus export file (only available with params.ab_initio=True)
params:
  - extra: additional program arguments
  - ab_initio: "run adapter inference before trimming (bool, default: False)"
