rule merge_vcfs:
    input:
        ["snvs.chr1.vcf", "snvs.chr2.vcf"]
    output:
        "snvs.vcf"
    log:
        "logs/picard/mergevcfs.log"
    params:
        java_options="-Xmx8g",
        extra=""
    wrapper:
        "master/bio/picard/mergevcfs"
