rule linear:
    input:
        multiext("plinkdata.", "fam", "map", "ped", "cov")
    output:
        "plinkdata.assoc.linear"
    params:
        extra_linear="standard-beta genotypic interaction --parameters 1-5, 7",
        extra_covar="keep-pheno-on-missing-cov",
        covariables=["binary_column", "case_control_with_missingness"]
    threads: 1
    log:
        "logs/plink/linear.log"
    wrapper:
        "master/bio/plink/linear"
