rule tabix:
    input:
        "{prefix}.vcf.gz",
    output:
        "{prefix}.vcf.gz.tbi",
    params:
        "-p vcf", # pass arguments to tabix (e.g. index a vcf)
    log:
        "logs/tabix/{prefix}.log",
    wrapper:
        "master/bio/tabix"
