rule mmseqs2_databases:
    output:
        db=multiext(
            "out/databases/{sample}",
            "",
            ".dbtype",
            ".index",
            ".lookup",
            ".source",
            ".version",
            "_h",
            "_h.dbtype",
            "_h.index",
            "_mapping",
            "_taxonomy",
        ),
    log:
        "logs/databases/{sample}.log",
    params:
        module="databases SILVA",
        extra="-v 3",
    threads: 1
    wrapper:
        "master/bio/mmseqs2/db"


rule mmseqs2_createdb:
    input:
        fas="seqs/{sample}.fasta",
    output:
        db=multiext(
            "out/createdb/{sample}",
            "",
            ".dbtype",
            ".index",
            ".lookup",
            ".source",
            "_h",
            "_h.dbtype",
            "_h.index",
        ),
    log:
        "logs/createdb/{sample}.log",
    params:
        module="createdb",
        extra="-v 3",
    threads: 1
    wrapper:
        "master/bio/mmseqs2/db"
