rule test_sd:
    input:
        "file.txt",
    output:
        "replaced.txt",
    log:
        "test_sd.log",
    threads: 1
    params:
        # Pattern to search in original text
        before="change /this/path",
        # Replacement pattern in the output text
        after="keep /that/one",
        # Any non-positional argument
        extra="",
    wrapper:
        "master/utils/sd"
