rule paladin_index:
    input:
        "prot.fasta", 
    output:
        "index/prot.fasta.bwt" 
    log:
        "logs/paladin/prot_index.log"
    threads: 4
    wrapper:
        "master/bio/paladin/index"
