
rule all:  # [hide]
    input:  # [hide]
        "multiqc/multiqc_report.html",  # [hide]


rule get_genome:  # [hide]
    output:  # [hide]
        "data/genome.fasta",  # [hide]
    shell:  # [hide]
        "curl -L https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/reference/genome.fa > {output}"  # [hide]


rule get_annotation:  # [hide]
    output:  # [hide]
        "data/genome.gtf",  # [hide]
    shell:  # [hide]
        "curl -L https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/reference/genes.gtf > {output}"  # [hide]


rule get_design:  # [hide]
    output:  # [hide]
        "design.csv",  # [hide]
    shell:  # [hide]
        "curl -L https://raw.githubusercontent.com/nf-core/test-datasets/chipseq/design.csv > {output}"  # [hide]


rule chipseq_pipeline:
    input:
        input="design.csv",
        fasta="data/genome.fasta",
        gtf="data/genome.gtf",
    output:
        "multiqc/multiqc_report.html",
    params:
        pipeline="nf-core/chipseq",
        revision="1.2.1",
        profile=["test", "conda"],
    wrapper:
        "master/utils/nextflow"
