rule mapdamage2_plot:
    input:
        bam="mapped/{sample}.bam",
        ref="genome.fasta",
    output:
        GtoA3p="results/plot/{sample}.3pGtoA_freq.txt",
        CtoT5p="results/plot/{sample}.5pCtoT_freq.txt",
        dnacomp="results/plot/{sample}.dnacomp.txt",
        lg_dist="results/plot/{sample}.lgdistribution.txt",
        misinc="results/plot/{sample}.misincorporation.txt",
        plot_misinc="results/plot/{sample}.Fragmisincorporation_plot.pdf",
        plot_len="results/plot/{sample}.Length_plot.pdf",
        log="results/plot/{sample}.log",
    params:
        extra="-m 20",
    log:
        "logs/plot/{sample}.log",
    threads: 1
    wrapper:
        "master/bio/mapdamage2"


rule mapdamage2_stats:
    input:
        GtoA3p=rules.mapdamage2_plot.output.GtoA3p,
        CtoT5p=rules.mapdamage2_plot.output.CtoT5p,
        misinc=rules.mapdamage2_plot.output.misinc,
        ref="genome.fasta",
    output:
        stats_ref="results/stats/{sample}.dnacomp_genome.csv",
        stats_prob="results/stats/{sample}.Stats_out_MCMC_correct_prob.csv",
        stats_hist="results/stats/{sample}.Stats_out_MCMC_hist.pdf",
        stats_iter="results/stats/{sample}.Stats_out_MCMC_iter.csv",
        stats_summ="results/stats/{sample}.Stats_out_MCMC_iter_summ_stat.csv",
        stats_plot_pred="results/stats/{sample}.Stats_out_MCMC_post_pred.pdf",
        stats_plot_trace="results/stats/{sample}.Stats_out_MCMC_trace.pdf",
        log="results/stats/{sample}.log",
    params:
        extra="--stats-only --burn 10 --iter 10",
    log:
        "logs/stats/{sample}.log",
    threads: 1
    wrapper:
        "master/bio/mapdamage2"


rule mapdamage2_rescale:
    input:
        bam="mapped/{sample}.bam",
        stats_prob=rules.mapdamage2_stats.output.stats_prob,
        ref="genome.fasta",
    output:
        bam="results/rescale/{sample}.bam",
        log="results/rescale/{sample}.log",
    params:
        extra="",
    log:
        "logs/rescale/{sample}.log",
    threads: 1
    wrapper:
        "master/bio/mapdamage2"


rule mapdamage2_all:
    input:
        bam="mapped/{sample}.bam",
        ref="genome.fasta",
    output:
        GtoA3p="resultsall/{sample}.3pGtoA_freq.txt",
        CtoT5p="resultsall/{sample}.5pCtoT_freq.txt",
        dnacomp="resultsall/{sample}.dnacomp.txt",
        lg_dist="resultsall/{sample}.lgdistribution.txt",
        misinc="resultsall/{sample}.misincorporation.txt",
        plot_misinc="resultsall/{sample}.Fragmisincorporation_plot.pdf",
        plot_len="resultsall/{sample}.Length_plot.pdf",
        stats_ref="results/all/{sample}.dnacomp_genome.csv",
        stats_prob="results/all/{sample}.Stats_out_MCMC_correct_prob.csv",
        stats_hist="results/all/{sample}.Stats_out_MCMC_hist.pdf",
        stats_iter="results/all/{sample}.Stats_out_MCMC_iter.csv",
        stats_summ="results/all/{sample}.Stats_out_MCMC_iter_summ_stat.csv",
        stats_plot_pred="results/all/{sample}.Stats_out_MCMC_post_pred.pdf",
        stats_plot_trace="results/all/{sample}.Stats_out_MCMC_trace.pdf",
        bam="results/all/{sample}.bam",
        log="results/all/{sample}.log",
    params:
        extra="--burn 10 --iter 10",
    log:
        "logs/all/{sample}.log",
    threads: 1
    wrapper:
        "master/bio/mapdamage2"
