rule lofreq_indelqual:
    input:
        bam="data/{sample}.bam",
    output:
        "out/indelqual/{sample}.indel.bam"
    log:
        "logs/{sample}.log"
    params:
        extra="-u 15"
    threads: 8
    wrapper:
        "master/bio/lofreq/indelqual"
