rule sickle_pe:
    input:
        "input_R1.fq",
    output:
        "output_R1.fq",
    params:
        qual_type="sanger",
        extra="", # optional extra parameters
    log:
        "logs/sickle/job.log",
    wrapper:
        "master/bio/sickle/pe"
