rule sickle_se:
  input:
    "reads/{sample}.1.fastq"
  output:
    "{sample}.1.fastq"
  log:
    "logs/sickle/{sample}.log"
  params:
    qual_type="sanger",
    # optional extra parameters
    extra=""
  wrapper:
    "master/bio/sickle/se"
