rule all:
    input:
        "abc.vcf",


rule test_jasminesv:
    input:
        vcfs=["a.vcf", "b.vcf", "c.vcf"],
    output:
        vcf="abc.vcf",
    log:
        "logs/jasminesv.log",
    threads: 1
    wrapper:
        "master/bio/jasminesv"
