rule gtfToGenePred:
    input:
        "annotation.gtf"
    output:
        "annotation.genePred"
    log:
        "logs/gtfToGenePred.log"
    params:
        extra="-genePredExt" # optional parameters to pass to gtfToGenePred
    wrapper:
        "master/bio/ucsc/gtfToGenePred"
