rule bbduk_se:
    input:
        sample=["reads/se/{sample}.fastq"],
        adapters="reads/adapt.fas",
    output:
        trimmed="trimmed/se/{sample}.fastq.gz",
        singleton="trimmed/se/{sample}.single.fastq.gz",
        discarded="trimmed/se/{sample}.discarded.fastq.gz",
        stats="trimmed/se/{sample}.stats.txt",
    log:
        "logs/bbduk/se/{sample}.log"
    params:
        extra = lambda w, input: "ref={},adapters,artifacts ktrim=r k=23 mink=11 hdist=1 tpe tbo trimpolygright=10 minlen=25 maxns=30 entropy=0.5 entropywindow=50 entropyk=5".format(input.adapters),
    resources:
        mem_mb=4000,
    threads: 7
    wrapper:
        "master/bio/bbtools/bbduk"


rule bbduk_pe:
    input:
        sample=["reads/pe/{sample}.1.fastq", "reads/pe/{sample}.2.fastq"],
        adapters="reads/adapt.fas",
    output:
        trimmed=["trimmed/pe/{sample}.1.fastq", "trimmed/pe/{sample}.2.fastq"],
        singleton="trimmed/pe/{sample}.single.fastq",
        discarded="trimmed/pe/{sample}.discarded.fastq",
        stats="trimmed/pe/{sample}.stats.txt",
    log:
        "logs/bbduk/pe/{sample}.log"
    params:
        extra = lambda w, input: "ref={},adapters,artifacts ktrim=r k=23 mink=11 hdist=1 tpe tbo trimpolygright=10 minlen=25 maxns=30 entropy=0.5 entropywindow=50 entropyk=5".format(input.adapters),
    resources:
        mem_mb=4000,
    threads: 7
    wrapper:
        "master/bio/bbtools/bbduk"
