rule tadpole_correct_se:
    input:
        sample=["reads/se/{sample}.fastq"],
    output:
        out="out/correct_se/{sample}.fastq.gz",
        discarded="out/correct_se/{sample}.discarded.fastq.gz",
    log:
        "logs/correct_se/{sample}.log",
    params:
        mode="correct",
        extra="",
    threads: 2
    resources:
        mem_mb=1024,
    wrapper:
        "master/bio/bbtools/tadpole"


rule tadpole_correct_pe:
    input:
        sample=["reads/pe/{sample}.1.fastq", "reads/pe/{sample}.2.fastq"],
    output:
        out=["out/correct_pe/{sample}.1.fastq", "out/correct_pe/{sample}.2.fastq"],
        discarded="out/correct_pe/{sample}.discarded.fastq",
    log:
        "logs/correct_pe/{sample}.log",
    params:
        mode="correct",
        extra="",
    threads: 2
    resources:
        mem_mb=1024,
    wrapper:
        "master/bio/bbtools/tadpole"


rule tadpole_extend_se:
    input:
        sample=["reads/se/{sample}.fastq"],
    output:
        out="out/extend_se/{sample}.fastq.gz",
        discarded="out/extend_se/{sample}.discarded.fastq.gz",
    log:
        "logs/extend_se/{sample}.log",
    params:
        mode="extend",
        extra="",
    threads: 2
    resources:
        mem_mb=1024,
    wrapper:
        "master/bio/bbtools/tadpole"


rule tadpole_extend_pe:
    input:
        sample=["reads/pe/{sample}.1.fastq", "reads/pe/{sample}.2.fastq"],
    output:
        out=["out/extend_pe/{sample}.1.fastq", "out/extend_pe/{sample}.2.fastq"],
        discarded="out/extend_pe/{sample}.discarded.fastq",
    log:
        "logs/extend_pe/{sample}.log",
    params:
        mode="extend",
        extra="",
    threads: 2
    resources:
        mem_mb=1024,
    wrapper:
        "master/bio/bbtools/tadpole"
