rule create_transcripts_to_genes_mapping:
    output:
        table="resources/ensembl_transcripts_to_genes_mapping.tsv.gz",  # .gz extension is optional, but recommended
    params:
        biomart="genes",
        species="homo_sapiens",
        build="GRCh38",
        release="112",
        columns=["ensembl_transcript_id", "ensembl_gene_id", "external_gene_name", "genecards"],
        # chromosom="22" # optional: restrict to single chromosome
    log:
        "logs/create_transcripts_to_genes_mapping.log",
    cache: "omit-software"  # save space and time with between workflow caching (see docs)
    wrapper:
        "master/bio/reference/ensembl-biomart-table"
