rule sourmash_reads:
    input:
        "reads/a.fastq",
    output:
        "reads.sig",
    log:
        "logs/sourmash/sourmash_compute_reads.log",
    threads: 2
    params:
        k="31", # optional parameters
        scaled="1000",
        extra="",
    wrapper:
        "master/bio/sourmash/compute"


rule sourmash_transcriptome:
    input:
        "assembly/transcriptome.fasta",
    output:
        "transcriptome.sig",
    log:
        "logs/sourmash/sourmash_compute_transcriptome.log",
    threads: 2
    params:
        k="31", # optional parameters
        scaled="1000",
        extra="",
    wrapper:
        "master/bio/sourmash/compute"
