rule genomepy:
    output:
        "{assembly}/{assembly}.fa",
        "{assembly}/{assembly}.fa.fai",
        "{assembly}/{assembly}.fa.sizes",
        "{assembly}/{assembly}.gaps.bed",
        "{assembly}/README.txt",
        # "{assembly}/{assembly}.annotation.gtf",  # uncomment to download
        # "{assembly}/{assembly}.blacklist.bed"    # uncomment to download
    log:
        "logs/genomepy_{assembly}.log"
    params:
        provider="NCBI"  # optional, defaults to ucsc. Choose from uccs, ensembl, and ncbi
    wrapper:
        "master/bio/genomepy"
