rule genomepy:
    output:
        multiext(
            "{assembly}/{assembly}",
            ".fa",
            ".fa.fai",
            ".fa.sizes",
            ".gaps.bed",
            ".annotation.gtf",
            ".blacklist.bed",
        ),
    log:
        "logs/genomepy_{assembly}.log",
    params:
        provider="ucsc",  # optional, defaults to ucsc. Choose from ucsc, ensembl, and ncbi
    cache: "omit-software"  # mark as eligible for between workflow caching
    wrapper:
        "master/bio/genomepy"
