
rule trinity:
    input:
        left=["reads/reads.left.fq.gz", "reads/reads2.left.fq.gz"],
        right=["reads/reads.right.fq.gz", "reads/reads2.right.fq.gz"],
    output:
        dir=temp(directory("trinity_out_dir/")),
        fas="trinity_out_dir.Trinity.fasta",
        map="trinity_out_dir.Trinity.fasta.gene_trans_map",
    log:
        'logs/trinity/trinity.log',
    params:
        extra="",
    threads: 4
    resources:
        mem_gb=10,
    wrapper:
        "master/bio/trinity"
