name: GFF3Validator
description: Tool to strictly validate given GFF3 files
url: https://github.com/genometools/genometools
authors:
  - Jorge Alvarez-Jarreta
input:
  - gff3: GFF3 file
output:
  - gff3: validated GFF3 file
notes: |
  * The `extra` param allows for additional program arguments.
