rule gatk_filter:
    input:
        vcf="calls/snvs.vcf",
        ref="genome.fasta",
#        intervals="targets.bed",
    output:
        vcf="calls/snvs.filtered.vcf",
    log:
        "logs/gatk/filter/snvs.log",
    params:
        filters={"myfilter": "AB < 0.2 || MQ0 > 50"},
        extra="",  # optional arguments, see GATK docs
        java_opts="",  # optional
    resources:
        mem_mb=1024,
    wrapper:
        "master/bio/gatk/variantfiltration"
