rule test_mashmap:
    input:
        ref="reference.fasta",
        query="read.fasta.gz"
    output:
        "mashmap.out"
    params:
        extra="-s 1000 --pi 99"
    log:
        "logs/mashmap.log"
    wrapper:
        "master/bio/mashmap"