rule annotate_variants:
    input:
        calls="variants.bcf",  # .vcf, .vcf.gz or .bcf
        cache="resources/vep/cache",
        plugins="resources/vep/plugins",
    output:
        calls="variants.annotated.bcf"  # .vcf, .vcf.gz or .bcf
    params:
        extra=""  # optional: extra arguments
    log:
        "logs/vep/annotate.log"
    wrapper:
        "master/bio/vep/annotate"
