rule bedGraphToBigWig:
    input:
        bedGraph="{sample}.bedGraph",
        chromsizes="genome.chrom.sizes"
    output:
        "{sample}.bw"
    log:
        "{sample}.bed-graph_to_big-wig.log"
    params:
        "" # optional params string
    wrapper:
        "master/bio/ucsc/bedGraphToBigWig"
