rule samtools_merge:
    input:
        ["mapped/A.bam", "mapped/B.bam"]
    output:
        "merged.bam"
    params:
        "" # optional additional parameters as string
    threads: 8
    wrapper:
        "0.2.0/bio/samtools/merge"
