rule test_pyfaidx_out_fasta:
    input:
        fasta="sequence.fasta",
        bed="interval.bed",
    output:
        "retrieved.fasta",
    threads: 1
    log:
        "test_pyfaidx.log",
    params:
        extra="--complement",
    wrapper:
        "master/bio/pyfaidx"


rule test_pyfaidx_index_fasta:
    input:
        fasta="sequence.fasta",
        bed="interval.bed",
    output:
        "sequence.fasta.fai",
    params:
        extra="",
    log:
        "test_pyfaidx_index_fasta.log",
    params:
        extra="--complement",
    wrapper:
        "master/bio/pyfaidx"


rule test_pyfaidx_out_sizes:
    input:
        fasta="sequence.fasta",
        bed="interval.bed",
    output:
        "retrieved.chrom",
    params:
        extra="",
    log:
        "test_pyfaidx_out_sizes.log",
    params:
        extra="--complement",
    wrapper:
        "master/bio/pyfaidx"


rule test_pyfaidx_out_bed:
    input:
        fasta="sequence.fasta",
        bed="interval.bed",
    output:
        "retrieved.bed",
    params:
        extra="",
    log:
        "test_pyfaidx_out_bed.log",
    params:
        extra="--complement",
    wrapper:
        "master/bio/pyfaidx"
