container: "docker://continuumio/miniconda3:4.4.10"

rule all:
    input:
        "assembly/assembly.fasta"


rule run_flye:
    input:
        reads="test_reads/ecoli_500kb_reads.fastq.gz"
    output:
        assembly="{dir_path}/assembly.fasta",
    benchmark:
        "logs/benchmarks/{dir_path}/flye.txt"
    params:
        seq_type="nano-raw",
        dir=lambda wildcards: wildcards.dir_path,
        extra="--iterations 1 --meta"
    log:
        "logs/{dir_path}/flye.log"
    threads: 8
    resources:
        mem_mb=250000,
    wrapper:
        "master/bio/flye"


rule download_test_reads:
    output:
        "test_reads/ecoli_500kb_reads.fastq.gz"
    log:
        "logs/download.log"
    shell:
        "wget -O {output} https://raw.githubusercontent.com/mikolmogorov/Flye/flye/flye/tests/data/ecoli_500kb_reads.fastq.gz >> {log} 2>&1"
