from snakemake.utils import min_version

min_version("9.13.1")


configfile: "config.yaml"


module gatk_mutect2_calling:
    meta_wrapper:
        "master/meta/bio/gatk_mutect2_calling"


use rule * from gatk_mutect2_calling
