rule create_repeat_annotations:
    output:
        table="resources/ensembl_repeat_annotations.tsv.gz",  # .gz extension is optional, but recommended
    params:
        species="homo_sapiens",
        build="GRCh37",
        release="105",
        main_tables={
            "repeat_feature": {
                "database": "core",
            },
        },  # choose the main table to retrieve, specifying { table : database }
        join_tables={
            "seq_region": {
                "database": "core",
                "join_column": "seq_region_id",
            },
            "repeat_consensus": {
                "database": "core",
                "join_column": "repeat_consensus_id",
            },
        },
        # optional: add tables to join in for further annotations, specifying { table : { "database": database, "join_column": join-column } }
    log:
        "logs/create_repeat_annotations.log",
    cache: "omit-software"  # save space and time with between workflow caching (see docs)
    wrapper:
        "master/bio/reference/ensembl-mysql-table"


rule create_regulatory_annotations_parquet:
    output:
        table="resources/ensembl_regulatory_annotations.parquet.gz",  # .gz extension is optional, but recommended
    params:
        species="mus_musculus",
        build="GRCm39",
        release="112",
        main_tables={
            "regulatory_feature": {
                "database": "funcgen",
            },
            "mirna_target_feature": {
                "database": "funcgen",
            },
        },
        # choose the main table to retrieve, specifying { table : database }
        join_tables={
            "seq_region": {
                "database": "core",
                "join_column": "seq_region_id"
            },
            "feature_type": {
                "database": "funcgen",
                "join_column": "feature_type_id"
            },
        },
        # optional: add tables to join in for further annotations, specifying { table : { "database": database, "join_column": join-column } }
    log:
        "logs/create_regulatory_annotations_parquet.log",
    cache: "omit-software"  # save space and time with between workflow caching (see docs)
    wrapper:
        "master/bio/reference/ensembl-mysql-table"
