rule paladin_align:
    input:
        r= ["reads/reads.left.fq.gz"], 
        index = "index/prot.fasta.bwt", 
    output:
        "paladin_mapped/{sample}.bam"
    log:
        "logs/paladin/{sample}.log"
    threads: 4
    wrapper:
        "master/bio/paladin/align"
