rule paladin_align:
    input:
        r=["reads/{sample}.1.fastq", "reads/{sample}.2.fastq"]
        index = "index/prot.fasta.bwt", 
    output:
        "paladin_mapped/{sample}.bam"
    log:
        "logs/paladin/{sample}.log"
    threads: 8
    wrapper:
        "master/bio/paladin/align"
