rule bismark_methylation_extractor:
    input: "{sample}.bam"
    output:
        mbias_report="{sample}.M-bias.txt",
        mbias_r1="{sample}.M-bias_R1.png",
        # Only for PE BAMS:
        # mbias_r2="{sample}.M-bias_R2.png",
        splitting_report="{sample}_splitting_report.txt",

        # 1-based start, 1-based end ('inclusive') methylation info: % and counts
        methylome_CpG_cov="{sample}.bismark.cov.gz",
        # BedGraph with methylation percentage: 0-based start, end exclusive
        methylome_CpG_mlevel_bedGraph="{sample}.bedGraph.gz",

        # Primary output files: methylation status at each read cytosine position: (extremely large)
        read_base_meth_state_cpg="CpG_context_{sample}.txt.gz",
        # * You could merge CHG, CHH using: --merge_non_CpG
        read_base_meth_state_chg="CHG_context_{sample}.txt.gz",
        read_base_meth_state_chh="CHH_context_{sample}.txt.gz"
    params:
        extra="--gzip --comprehensive --bedGraph"  # optional params string
    wrapper:
        "master/bio/bismark/bismark_methylation_extractor"
