rule merge:
    input:
        "input/{assembly}.fasta",
        "input/{scaffolds1}.agp",
        "input/{scaffolds2}.agp",
    output:
        fasta="{assembly}_merge_{scaffolds1}_{scaffolds2}.fasta",
        agp="{assembly}_merge_{scaffolds1}_{scaffolds2}.agp",
        #links = "{assembly}_merge_{scaffolds1}_{scaffolds2}.links",
    params:
        extra="",
    log:
        "logs/ragtag/{assembly}_merge_{scaffolds1}_{scaffolds2}.log",
    wrapper:
        "master/bio/ragtag/merge"
