rule alignoth_json:
    input:
        bam="NA12878.bam",
        reference="ref.fa",
        vcf="1257A.vcf.gz"
    output:
        "out/json_plot.vl.json"
    params:
        extra="-g 1:50-280 -h coolregion:200-210"
    log:
        "logs/log.txt"
    wrapper:
        "master/bio/alignoth"

rule alignoth_tsv:
    input:
        bam="NA12878.bam",
        reference="ref.fa",
        vcf="1257A.vcf.gz"
    output:
        "out/plot.html"
    params:
        extra="-g 1:50-280 -h coolregion:200-210"
    log:
        "logs/log.txt"
    wrapper:
        "master/bio/alignoth"

rule alignoth_output_dir:
    input:
        bam="NA12878.bam",
        reference="ref.fa",
        vcf="1257A.vcf.gz"
    output:
        "output-dir/"
    params:
        extra="-g 1:50-280 -h coolregion:200-210"
    log:
        "logs/log.txt"
    wrapper:
        "master/bio/alignoth"
