rule deeptools_bampe_fragmentsize:
    input:
        # Input BAM file(s)
        bams=["a.bam", "b.bam"],
        # Optional blacklist file
        # blacklist="",
    output:
        # Please note that -o/hist/--histogram and --outRawFragmentLengths are exclusively defined via output files.
        # Usable output variables, their extensions and which option they implicitly call are listed here:
        # https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/deeptools/bamPEFragmentSize.html.
        # Required
        hist="results/histogram.png",
        # Optional output files
        raw="results/raw.tab",
    log:
        "logs/deeptools/bampe_fragmentsize.log",
    threads: 4
    params:
        # Labels can be changed to anything
        # If left empty, the sample name will be used 
        # (without path and .bam extension)
        labels="",  
        extra="--logScale",
    wrapper:
        "master/bio/deeptools/bampefragmentsize"
