rule samtools_sort:
    input:
        "mapped/{sample}.bam",
    output:
        "mapped/{sample}.sorted.bam",
    params:
        extra="-m 4G",
        tmp_dir="/tmp/",
    threads: 2 # Samtools takes additional threads through its option -@, the value specified here minus 1 will be sent to -@.
    wrapper:
        "master/bio/samtools/sort"
