rule samtools_sort:
    input:
        "mapped/{sample}.bam",
    output:
        "mapped/{sample}.sorted.bam",
    log:
        "logs/{sample}.log",
    params:
        extra="",
    threads: 8
    resources:
        mem="64G",  # choose as required, the more the better
    wrapper:
        "master/bio/samtools/sort"
