rule mpilup:
    input:
        bam="mapped/{sample}.bam", # single or list of bam files
        reference_genome="genome.fasta",
    output:
        "mpileup/{sample}.mpileup.gz",
    log:
        "logs/samtools/mpileup/{sample}.log",
    params:
        extra="-d 10000", # optional
    wrapper:
        "master/bio/samtools/mpileup"
