rule get_genome_fasta:
    output:
        "genome.fasta",
    threads: 1
    log:
        "logs/get_genome_fasta.log",
    params:
        species="saccharomyces_cerevisiae",
        datatype="dna",
        build="R64-1-1",
        release="105",
    wrapper:
        "master/bio/reference/ensembl-sequence"


rule samtools_mpileup:
    input:
        bam=expand(
            "{sample}.sorted.bam",
            sample=("a", "b"),
        ),
        reference_genome="genome.fasta",
    output:
        "samtools/mpileup.gz",
    threads: 1
    log:
        "logs/samtools_mpileup.log",
    params:
        extra=" --count-orphans ",
    wrapper:
        "master/bio/samtools/mpileup"


rule varscan2_somatic:
    input:
        mpileup="samtools/mpileup.gz",
    output:
        snp="varscan2/snp.vcf",
        indel="varscan2/indel.vcf",
    threads: 1
    log:
        "logs/varscan2_somatic.log",
    params:
        extra=" --strand-filter 1 ",
    wrapper:
        "master/bio/varscan/somatic"


rule snpeff_download:
    output:
        directory("resources/snpeff/R64-1-1.105"),
    threads: 1
    log:
        "logs/snpeff_download.log",
    params:
        reference="R64-1-1.105",
    wrapper:
        "master/bio/snpeff/download"


rule snpeff_annotate:
    input:
        calls="varscan2/snp.vcf",
        db="resources/snpeff/R64-1-1.105",
    output:
        calls="snpeff/annotated.vcf",
        stats="snpeff/annotated.html",
        csvstats="snpeff/annotated.csv",
    threads: 1
    log:
        "logs/snpeff_annotate.log",
    params:
        extra=" -nodownload -noLog ",
    wrapper:
        "master/bio/snpeff/annotate"
