rule test_gseapy_enrichr:
    input:
        gene_list="genes_list.txt",
        # gmt="", Optional path to a GMT file
    output:
        directory("results_enrichr"),
    threads: 1
    params:
        extra={"cutoff": 1},
        gene_sets = ["KEGG_2016"] # Optional list of gene sets available on biomart
    log:
        "logs/gseapy/enrichr.log"
    wrapper:
        "master/bio/gseapy/gsea"


rule test_gseapy_gsea:
    input:
        expr="genes_expr.tsv",
        cls="sample_class.cls",
        gmt="geneset.gmt",
    output:
        directory("results_gsea"),
    threads: 1
    params:
        extra={
            "min_size": 1,
            "permutation_num": 2,
            "method": 't_test',
        },
        # gene_sets = [""] # Optional list of gene sets available on biomart
    log:
        "logs/gseapy/gsea.log"
    wrapper:
        "master/bio/gseapy/gsea"


rule test_gseapy_ssgsea:
    input:
        expr="genes_expr.tsv",
        gmt="geneset.gmt",
    output:
        directory("results_ssgsea"),
    threads: 1
    params:
        extra={
            "min_size": 1
        },
        # gene_sets = [""] # Optional list of gene sets available on biomart
    log:
        "logs/gseapy/ssgsea.log"
    wrapper:
        "master/bio/gseapy/gsea"


rule test_gseapy_prerank:
    input:
        rank="genes.rnk",
        gmt="geneset.gmt",
    output:
        directory("results_prerank"),
    threads: 1
    params:
        extra={
            "min_size": 1
        },
        # gene_sets = [""] # Optional list of gene sets available on biomart
    log:
        "logs/gseapy/prerank.log"
    wrapper:
        "master/bio/gseapy/gsea"