rule test_gseapy_enrichr:
    input:
        gene_list="genes_list.txt",
        # gmt="", Optional path to a GMT file
    output:
        enrichr_dir=directory("KEGG_2016"),
    threads: 1
    params:
        extra={"cutoff": 1},
        gene_sets=["KEGG_2016"],  # Optional list of gene sets available on biomart
    log:
        wrapper="logs/gseapy/wrapper.enrichr.log",
        gseapy="logs/gseapy/enrichr.log",
    wrapper:
        "master/bio/gseapy/gsea"


rule test_gseapy_gsea:
    input:
        expr="genes_expr.tsv",
        cls="sample_class.cls",
        gmt="geneset.gmt",
    output:
        gmt="gene_sets.gmt",
        csv="gsea.results.csv",
    threads: 1
    params:
        extra={
            "min_size": 1,
        },
        # gene_sets = [""] # Optional list of gene sets available on biomart
    log:
        wrapper="logs/gseapy/wrapper.gsea.log",
        gseapy="logs/gseapy/gsea.log",
    wrapper:
        "master/bio/gseapy/gsea"


rule test_gseapy_ssgsea:
    input:
        expr="genes_expr.tsv",
        gmt="geneset.gmt",
    output:
        gmt="gene_sets.gmt",
        csv="ssgsea.results.csv",
    threads: 1
    params:
        extra={
            "min_size": 1,
        },
        # gene_sets = [""] # Optional list of gene sets available on biomart
    log:
        wrapper="logs/gseapy/wrapper.ssgsea.log",
        gseapy="logs/gseapy/ssgsea.log",
    wrapper:
        "master/bio/gseapy/gsea"


rule test_gseapy_prerank:
    input:
        rank="genes.rnk",
        gmt="geneset.gmt",
    output:
        gmt="gene_sets.gmt",
        csv="prerank.results.csv",
        prerank=directory("prerank_results_dir"),
    threads: 1
    params:
        extra={
            "min_size": 1,
        },
        # gene_sets = [""] # Optional list of gene sets available on biomart
    log:
        wrapper="logs/gseapy/wrapper.prerank.log",
        gseapy="logs/gseapy/prerank.log",
    wrapper:
        "master/bio/gseapy/gsea"
