rule test_gseapy_enrichr:
    input:
        gene_list="genes_list.txt",
        # gmt="", Optional path to a GMT file
    output:
        enrichr_dir=directory("out/enrichr/KEGG_2016"),
    log:
        wrapper="logs/enrichr.wrapper.log",
        gseapy="logs/enrichr.log",
    threads: 1
    params:
        extra={"cutoff": 1},
        gene_sets=["KEGG_2016"],  # Optional list of gene sets available on biomart
    wrapper:
        "master/bio/gseapy/gsea"


rule test_gseapy_gsea:
    input:
        expr="genes_expr.tsv",
        cls="sample_class.cls",
        gmt="geneset.gmt",
    output:
        gmt="out/gsea/gene_sets.gmt",
        csv="out/gsea/results.csv",
    log:
        wrapper="logs/gsea.wrapper.log",
        gseapy="logs/gsea.log",
    threads: 1
    params:
        extra={
            "min_size": 1,
        },
        # gene_sets = [""] # Optional list of gene sets available on biomart
    wrapper:
        "master/bio/gseapy/gsea"


rule test_gseapy_ssgsea:
    input:
        expr="genes_expr.tsv",
        gmt="geneset.gmt",
    output:
        gmt="out/ssgsea/gene_sets.gmt",
        csv="out/ssgsea/results.csv",
    log:
        wrapper="logs/ssgsea.wrapper.log",
        gseapy="logs/ssgsea.log",
    threads: 1
    params:
        extra={
            "min_size": 1,
        },
        # gene_sets = [""] # Optional list of gene sets available on biomart
    wrapper:
        "master/bio/gseapy/gsea"


rule test_gseapy_prerank:
    input:
        rank="genes.rnk",
        gmt="geneset.gmt",
    output:
        gmt="out/prerank/gene_sets.gmt",
        csv="out/prerank/results.csv",
        prerank=directory("out/prerank/results_dir"),
    log:
        wrapper="logs/prerank.wrapper.log",
        gseapy="logs/prerank.log",
    threads: 1
    params:
        extra={
            "min_size": 1,
        },
        # gene_sets = [""] # Optional list of gene sets available on biomart
    wrapper:
        "master/bio/gseapy/gsea"
