name: Optitype
description: Precision 4-digit HLA-I-typing from NGS data based on integer linear programming. Use razers3 beforehand to generate input fastq files only mapping to HLA-regions.
url: https://github.com/FRED-2/OptiType
authors:
  - Jan Forster
input:
  - reads: input FASTQ files
  - config: config.ini file 
output:
  - tsv: HLA typing results
  - pdf: coverage plot
params:
  - sequencing_type: type of sequencing data
  - extra: additional program arguments
