rule sickle_pe:
  input:
    r1="reads/{sample}.1.fq",
    r2="reads/{sample}.2.fq"
  output:
    r1="{sample}.1.fq",
    r2="{sample}.2.fq",
    rs="{sample}.single.fq",
  log:
    "logs/sickle/{sample}.log"
  params:
    qual_type="sanger",
    # optional extra parameters
    extra=""
  wrapper:
    "master/bio/sickle/pe"
