rule nonpareil:
    input:
        "reads/{sample}",
    output:
        redund_sum="results/{sample}.npo",
        redund_val="results/{sample}.npa",
        mate_distr="results/{sample}.npc",
        log="results/{sample}.log",
    log:
        "logs/{sample}.log",
    params:
        alg="kmer",
        infer_X=True,
        extra="-k 3 -F",
    threads: 2
    resources:
        mem_mb=50,
    wrapper:
        "master/bio/nonpareil/infer"
