rule bcftools_index:
    input:
        "a.bcf",
    output:
        "a.bcf.csi",
    log:
        "index/a.log",
    params:
        extra="",  # optional parameters for bcftools index
    wrapper:
        "master/bio/bcftools/index"
