name: GFF3
description: Tool to parse, possibly transform, and output GFF3 files
url: https://github.com/genometools/genometools
authors:
  - Jorge Alvarez-Jarreta
input:
  - GFF3 file
output:
  - output GFF3 file
params:
  - extra: additional program arguments.
