rule run_merqury_haploid:
    input:
        fasta="hap1.fasta",
        meryldb="meryldb",
    output:
        meryldb_filt="results/haploid/meryldb.filt",
        meryldb_hist="results/haploid/meryldb.hist",
        meryldb_hist_ploidy="results/haploid/meryldb.hist.ploidy",
        completeness_stats="results/haploid/out.completeness.stats",
        dist_only_hist="results/haploid/out.dist.only.hist",
        qv="results/haploid/out.qv",
        spectra_asm_hist="results/haploid/out.spectra_asm.hist",
        spectra_asm_ln_png="results/haploid/out.spectra_asm.png",
        fas1_only_bed="results/haploid/hap1.bed",
        fas1_only_wig="results/haploid/hap1.wig",
        fas1_only_hist="results/haploid/hap1.hist",
        fas1_qv="results/haploid/hap1.qv",
        fas1_spectra_hist="results/haploid/hap1.spectra.hist",
        fas1_spectra_ln_png="results/haploid/hap1.spectra.png",
        logs=directory("logs/haploid/"),
    log:
        "logs/haploid.log",
    threads: 1
    shadow:
        "minimal"
    wrapper:
        "master/bio/merqury"


rule run_merqury_diploid:
    input:
        fasta=["hap1.fasta", "hap2.fasta"],
        meryldb="meryldb",
    output:
        meryldb_filt="results/diploid/meryldb.filt",
        meryldb_hist="results/diploid/meryldb.hist",
        meryldb_hist_ploidy="results/diploid/meryldb.hist.ploidy",
        completeness_stats="results/diploid/out.completeness.stats",
        dist_only_hist="results/diploid/out.dist.only.hist",
        only_hist="results/diploid/out.only.hist",
        qv="results/diploid/out.qv",
        spectra_asm_hist="results/diploid/out.spectra_asm.hist",
        spectra_asm_ln_png="results/diploid/out.spectra_asm.png",
        spectra_cn_hist="results/diploid/out.spectra_cn.hist",
        spectra_cn_ln_png="results/diploid/out.spectra_cn.png",
        fas1_only_bed="results/diploid/hap1.bed",
        fas1_only_wig="results/diploid/hap1.wig",
        fas1_only_hist="results/diploid/hap1.hist",
        fas1_qv="results/diploid/hap1.qv",
        fas1_spectra_hist="results/diploid/hap1.spectra.hist",
        fas1_spectra_ln_png="results/diploid/hap1.spectra.png",
        fas2_only_bed="results/diploid/hap2.bed",
        fas2_only_wig="results/diploid/hap2.wig",
        fas2_only_hist="results/diploid/hap2.hist",
        fas2_qv="results/diploid/hap2.qv",
        fas2_spectra_hist="results/diploid/hap2.spectra.hist",
        fas2_spectra_ln_png="results/diploid/hap2.spectra.png",
        logs=directory("logs/diploid/"),
    log:
        "logs/diploid.log",
    threads: 1
    shadow:
        "minimal"
    wrapper:
        "master/bio/merqury"
