rule run_merqury_haploid:
    input:
        fasta="hap1.fasta",
        meryldb="meryldb",
    output:
        # meryldb output
        filt="results/haploid/meryldb.filt",
        hist="results/haploid/meryldb.hist",
        hist_ploidy="results/haploid/meryldb.hist.ploidy",
        # general output
        completeness_stats="results/haploid/out.completeness.stats",
        dist_only_hist="results/haploid/out.dist.only.hist",
        qv="results/haploid/out.qv",
        spectra_asm_hist="results/haploid/out.spectra_asm.hist",
        spectra_asm_ln_png="results/haploid/out.spectra_asm.png",
        # haplotype-specific output
        fas1_only_bed="results/haploid/hap1.bed",
        fas1_only_wig="results/haploid/hap1.wig",
        fas1_only_hist="results/haploid/hap1.hist",
        fas1_qv="results/haploid/hap1.qv",
        fas1_spectra_cn_hist="results/haploid/hap1.spectra.hist",
        fas1_spectra_cn_ln_png="results/haploid/hap1.spectra.png",
    log:
        std="logs/haploid.log",
        spectra_cn="logs/haploid.spectra-cn.log",
    threads: 1
    wrapper:
        "master/bio/merqury"


rule run_merqury_diploid:
    input:
        fasta=["hap1.fasta", "hap2.fasta"],
        meryldb="meryldb",
    output:
        # meryldb output
        filt="results/diploid/meryldb.filt",
        hist="results/diploid/meryldb.hist",
        hist_ploidy="results/diploid/meryldb.hist.ploidy",
        # general output
        completeness_stats="results/diploid/out.completeness.stats",
        dist_only_hist="results/diploid/out.dist.only.hist",
        only_hist="results/diploid/out.only.hist",
        qv="results/diploid/out.qv",
        spectra_asm_hist="results/diploid/out.spectra_asm.hist",
        spectra_asm_ln_png="results/diploid/out.spectra_asm.png",
        spectra_cn_hist="results/diploid/out.spectra_cn.hist",
        spectra_cn_ln_png="results/diploid/out.spectra_cn.png",
        # haplotype-specific output
        fas1_only_bed="results/diploid/hap1.bed",
        fas1_only_wig="results/diploid/hap1.wig",
        fas1_only_hist="results/diploid/hap1.hist",
        fas1_qv="results/diploid/hap1.qv",
        fas1_spectra_cn_hist="results/diploid/hap1.spectra.hist",
        fas1_spectra_cn_ln_png="results/diploid/hap1.spectra.png",
        fas2_only_bed="results/diploid/hap2.bed",
        fas2_only_wig="results/diploid/hap2.wig",
        fas2_only_hist="results/diploid/hap2.hist",
        fas2_qv="results/diploid/hap2.qv",
        fas2_spectra_cn_hist="results/diploid/hap2.spectra.hist",
        fas2_spectra_cn_ln_png="results/diploid/hap2.spectra.png",
    log:
        std="logs/diploid.log",
        spectra_cn="logs/diploid.spectra-cn.log",
    threads: 1
    wrapper:
        "master/bio/merqury"
