rule dada2_filter_trim_pe:
    input:
        # Paired-end files without primers sequences
        fwd="trimmed/{sample}.1.fastq",
        rev="trimmed/{sample}.2.fastq"
    output:
        filt="filtered/{sample}.1.fastq",
        filt_rev="filtered/{sample}.2.fastq",
        stats="reports/dada2/filter-trim/{sample}.tsv"
    log:
        "logs/dada2/filter-trim/{sample}.log"
    params:
        {'maxEE':1, # Max expected errors allowed in the filtered sequences
            'truncLen': [7,6], # List of 2 with the number of kept bases (0 for no truncation)
            'minLen':1 # Set to 1 for the toy example but default is 20
        }
    threads: 1 # set desired number of threads here
    wrapper:
        "master/bio/dada2/filter-trim-pe"
