rule snpeff:
    input:
        calls="{sample}.vcf", # (vcf, bcf, or vcf.gz)
        db="resources/snpeff/ebola_zaire" # path to reference db downloaded with the snpeff download wrapper
    output:
        calls="snpeff/{sample}.vcf",   # annotated calls (vcf, bcf, or vcf.gz)
        stats="snpeff/{sample}.html",  # summary statistics (in HTML), optional
        csvstats="snpeff/{sample}.csv" # summary statistics in CSV, optional
    log:
        "logs/snpeff/{sample}.log"
    resources:
        java_opts="-XX:ParallelGCThreads=10",
        mem_mb=4096
    wrapper:
        "master/bio/snpeff/annotate"

rule snpeff_nostats:
    input:
        calls="{sample}.vcf",
        db="resources/snpeff/ebola_zaire"
    output:
        calls="snpeff_nostats/{sample}.vcf",    # the main output file
        # if either "genes" or "stats" outputs are provided, both are created
    log:
        "logs/snpeff_nostats/{sample}.log"
    params:
        java_opts="-XX:ParallelGCThreads=10",
        extra=""                 # optional parameters
    resources:
        mem_mb=1024
    wrapper:
        "master/bio/snpeff/annotate"