rule dada2_filter_trim_se:
    input:
        # Paired-end files without primers sequences
        fwd="trimmed/{sample}.1.fastq",
    output:
        filt="filtered/{sample}.1.fastq",
        stats="reports/dada2/filter-trim/{sample}.tsv"
    log:
        "logs/dada2/filter-trim/{sample}.log"
    params:
        {'maxEE':1, # Max expected errors allowed in the filtered sequences
            'truncLen': 7, # The number of kept bases (0 for no truncation)
            'minLen':1 # Set to 1 for the toy example but default is 20
        }
    threads: 1 # set desired number of threads here
    wrapper:
        "master/bio/dada2/filter-trim"
