rule hisat2_index:
    input:
        fasta = "{genome}.fasta"
    output:
        directory("index_{genome}")
    params:
        prefix = "{genome}"
    log:
        "logs/hisat2_index_{genome}.log"
    threads: 2
    wrapper:
        "master/bio/hisat2/index"
