rule ptrimmer_pe:
    input:
        r1="resources/a.lane1_R1.fq.gz",
        r2="resources/a.lane1_R2.fq.gz"
    output:
        r1="results/a.lane1_R1.fq.gz",
        r2="results/a.lane1_R1.fq.gz"
    params:
        primers="resources/primers.txt"
    wrapper:
        "file:bio/ptrimmer"