rule printreads:
    input:
        bam="mapped/{sample}.bam",
        ref="genome.fasta",
        recal_data="{sample}.recal_data_table"
    output:
        "alignment/{sample}.bqsr.bam"
    log:
        "logs/gatk/bqsr/{sample}..log"
    params:
        extra=""  # optional
    resources:
        mem_mb = 1024
    threads: 16
    wrapper:
        "bio/gatk3/printreads"
