rule deduplicate_bismark:
    input: "bams/{sample}.bam"
    output:
        bam="bams/{sample}.deduplicated.bam",
        report="bams/{sample}.deduplication_report.txt",
    log:
        "logs/bams/{sample}.deduplicated.log",
    params:
        extra=""  # optional params string
    wrapper:
        "master/bio/bismark/deduplicate_bismark"
