import bioframe
import cooltools

# this file is 145 Mb, and may take a few seconds to download
cool_file = cooltools.download_data("HFF_MicroC", cache=True, data_dir="./")


rule cooltools_dots:
    input:
        cooler=cool_file,  ## Multiresolution cooler file
        expected="test_expected.tsv",  ## Expected file
        view="test_view.txt",  ## File with the region names and coordinates
    output:
        "CN_{resolution,[0-9]+}.dots.bedpe",
    params:
        ## Add optional parameters 
        extra="",  ## Add extra parameters
    threads: 4
    log:
        "logs/CN_{resolution}_dots.log",
    wrapper:
        "master/bio/cooltools/dots"
