rule test_yq_concat:
    input:
        ["bazquux.yaml", "foobar.yaml"],
    output:
        "concat.yaml",
    threads: 1
    log:
        "test_yq_concat.log",
    params:
        extra="",
        subcommand="",
        expression="",
    wrapper:
        "master/utils/go-yq"


rule test_yq_simple_yaml_update:
    input:
        "foobar.yaml",
    output:
        "updated.yaml",
    threads: 1
    log:
        "test_yq_simple_yaml_update.log",
    params:
        extra="",
        subcommand="",
        expression='.[].foo = "foobar"',
    wrapper:
        "master/utils/go-yq"


rule test_yq_evaluate_yaml_content:
    input:
        "eval.yaml",
    output:
        "evaluated.yaml",
    threads: 1
    log:
        "test_yq_evaluate_yaml_content.log",
    params:
        extra="",
        subcommand="",
        expression="eval(.pathExp)",
    wrapper:
        "master/utils/go-yq"


rule test_yq_split_yaml:
    input:
        "concat.yaml",
    output:
        "foo_bar.yml",
        "foo_bar2.yml",
    threads: 1
    log:
        "test_yq_split_yaml.log",
    params:
        extra="-s '\"foo_\" + .foo'",
        subcommand="",
        expression=".[]",
    wrapper:
        "master/utils/go-yq"


rule test_yq_format_conversion:
    input:
        "table.csv",
    output:
        "table.json",
    threads: 1
    log:
        "test_yq_format_conversion.log",
    params:
        extra="",
        subcommand="",
        expression="",
    wrapper:
        "master/utils/go-yq"
