rule verify_bam_id:
    input:
        bam="a.bam",
        ref="genome.fasta",
    output:
        selfsm="a.selfSM",
        ancestry="a.ancestry",
    params:
        # optional - this can be used to specify custom resource files if
        # necessary (if using GRCh37 or GRCh38 instead simply specify
        # genome_build="38", for example
        svd_prefix="ref.vcf",
        #genome_build="38",
    log:
        "logs/verifybamid2/a.log",
    wrapper:
        "master/bio/verifybamid/verifybamid2"
