rule combine_outputs:
    input:
        expand("{sample}_rel-abundance.tsv", sample=["sample1", "sample2"]),
    output:
        "combined_abundances.tsv",
    log:
        "logs/emu/combined_abundances.log",
    wrapper:
        "master/bio/emu/combine-outputs"


rule combine_outputs_split:
    input:
        expand("{sample}_rel-abundance.tsv", sample=["sample1", "sample2"]),
    output:
        abundance="counts.tsv",
        taxonomy="taxonomy.tsv",
    log:
        "logs/emu/combined_split.log",
    params:
        rank="genus",
        extra="--counts",
    wrapper:
        "master/bio/emu/combine-outputs"
