rule get_annotation:
    output:
        "refs/annotation.gtf"
    params:
        species="homo_sapiens",
        release="98",
        build="GRCh38",
        fmt="gtf"
    log:
        "logs/get_annotation.log"
    wrapper:
        "master/bio/reference/ensembl-annotation"
