rule get_annotation:
    output:
        "refs/annotation.gtf",
    params:
        species="homo_sapiens",
        release="105",
        build="GRCh37",
        flavor="",  # optional, e.g. chr_patch_hapl_scaff, see Ensembl FTP.
    log:
        "logs/get_annotation.log",
    cache: "omit-software"  # save space and time with between workflow caching (see docs)
    wrapper:
        "master/bio/reference/ensembl-annotation"


rule get_annotation_gz:
    output:
        "refs/annotation.gtf.gz",
    params:
        species="homo_sapiens",
        release="105",
        build="GRCh37",
        flavor="",  # optional, e.g. chr_patch_hapl_scaff, see Ensembl FTP.
    log:
        "logs/get_annotation.log",
    cache: "omit-software"  # save space and time with between workflow caching (see docs)
    wrapper:
        "master/bio/reference/ensembl-annotation"


rule get_off_branch_annotation:
    output:
        "refs/off_branch_annotation.gtf",
    params:
        species="bacillus_subtilis_subsp_subtilis_str_168_gca_000009045",
        release="59", # note latest release varies with url
        build="ASM904v1",
        branch="bacteria", # optional for off branch genomes
        url="ftp://ftp.ensemblgenomes.org/pub/", # optional set ftp server source
        collection="bacteria_0_collection", # optional set collection source for genome
    log:
        "logs/get_off_branch_annotation.log",
    cache: "omit-software"  # save space and time with between workflow caching (see docs)
    wrapper:
        "master/bio/reference/ensembl-annotation"
