rule transdecoder:
    input:
        fasta="test.fa.gz",  # required
        gene_trans_map="test.gtm",  # optional gene-to-transcript identifier mapping file (tab-delimited, gene_id<tab>trans_id<return> )
    output:
        "test.fa.transdecoder_dir/longest_orfs.pep" "test.fa.transdecoder.bed",
        "test.fa.transdecoder.cds",
        "test.fa.transdecoder.pep",
        "test.fa.transdecoder.gff3",
    log:
        "logs/transdecoder.log",
    params:
        extra="-m 100",
    wrapper:
        "master/bio/transdecoder"
