rule pbmarkdup:
    input:
        "reads.fastq.gz",
    output:
        dedup="pbmarkdup1.fastq.gz",
    log:
        "logs/pbmarkdup.log",
    params:
        extra="",
    wrapper:
        "master/bio/pbmarkdup"


rule pbmarkdup_dedup:
    input:
        "reads.fastq.gz",
    output:
        dedup="pbmarkdup2.fastq.gz",
        dup="dedup.fastq.gz",
    log:
        "logs/pbmarkdup_dedup.log",
    params:
        extra="",
    wrapper:
        "master/bio/pbmarkdup"


rule pbmarkdup_rmdup:
    input:
        reads="reads.fastq.gz",
    output:
        "pbmarkdup3.fastq.gz",
        dup="reads.fastq.gz",
    log:
        "logs/pbmarkdup_rmdup.log",
    params:
        extra="--rmdup",
    wrapper:
        "master/bio/pbmarkdup"
