rule bwa_index:
    input:
        "{genome}.fasta"
    output:
        index = multiext("{genome}", ".amb", ".ann", ".bwt", ".pac", ".sa")
    log:
        "logs/bwa_index/{genome}.log"
    params:
        algorithm="bwtsw"
    wrapper:
        "master/bio/bwa/index"
