rule bwa_index:
    input:
        "{genome}.fasta",
    output:
        idx=multiext("{genome}", ".amb", ".ann", ".bwt", ".pac", ".sa"),
    log:
        "logs/bwa_index/{genome}.log",
    params:
        extra="-a bwtsw",
    wrapper:
        "master/bio/bwa/index"
