rule bwa_mem:
    input:
        reads=["reads/{sample}.1.fastq", "reads/{sample}.2.fastq"]
    output:
        bam="mapped/{sample}.bam",
        index="mapped/{sample}.bam.bai"
    log:
        "logs/bwa_mem2_sambamba/{sample}.log"
    params:
        index="genome.fasta",
        extra=r"-R '@RG\tID:{sample}\tSM:{sample}'",
        sort_extra="" # Extra args for sambamba.
    threads: 8
    wrapper:
        #"master/bio/bwa-mem2/mem-samblaster"
        "file:/vol/huge/christo/snakemake-wrappers/bio/bwa-mem2/mem-samblaster"
