rule seqtk_mergepe:
    input:
        r1="{sample}.1.fastq.gz",
        r2="{sample}.2.fastq.gz",
    output:
        merged="{sample}.merged.fastq.gz",
    params:
        compress_lvl=9,
    log:
        "logs/seqtk_mergepe/{sample}.log",
    threads: 2
    wrapper:
        "master/bio/seqtk/mergepe"
