rule assoc:
    input:
        multiext("plinkdata.", "fam", "map", "ped")
    output:
        multiext("plinkdata.", "assoc.fisher", "assoc.fisher.mperm")
    params:
        extra_assoc="fisher-midp mperm=5000 --hwe 1e-8 midp --seed 9034"
    threads: 1
    log:
        "logs/plink/assoc.log"
    wrapper:
        "master/bio/plink/assoc"

rule qassoc:
    input:
        multiext("plinkQdata.", "fam", "map", "ped")
    output:
        multiext("plinkQdata.", "assoc", "assoc.mperm")
    params:
        extra_assoc="mperm=5000 --hwe 1e-8 midp --seed 9034"
    threads: 1
    log:
        "logs/plink/qassoc.log"
    wrapper:
        "master/bio/plink/assoc"
