rule get_vep_cache:
    output:
        directory("resources/vep/cache")
    params:
        species="saccharomyces_cerevisiae",
        build="R64-1-1",
        release="98"
    log:
        "logs/vep/cache.log"
    wrapper:
        "master/bio/vep/cache"
