rule get_vep_cache:
    output:
        directory("resources/vep/cache/{species}/{release}_{build}")
    log:
        "logs/vep/cache/{species}/{release}_{build}.log"
    cache: True  # save space and time with between workflow caching (see docs)
    wrapper:
        "master/bio/vep/cache"
