rule cooltools_insulation:
    input:
        cooler="CN.mm9.1000kb.mcool",
    output:
        "{sample}_{resolution,[0-9]+}.insulation.tsv"
    params:
        ## Add optional parameters 
        window=[10000000, 12000000], ## In this example, we test with two window sizes
        chunksize=20000000
    log:
        "logs/insulation/{sample}_{resolution}_insulation.log"
    wrapper:
        "file:../wrapper.py"
