rule cooltools_insulation:
    input:
        cooler="CN.mm9.1000kb.mcool", ## Multiresolution cooler file
    output:
        "{sample}_{resolution,[0-9]+}.insulation.tsv"
    params:
        ## Add optional parameters 
        window=[10000000, 12000000], ## In this example, we test with two window sizes
        chunksize=20000000, ## How many pixels are loaded in memory at once
        view="mm9_view.txt", ## File with the chromosome names and lengths
    threads: 4 ## Number of threads to use
    log:
        "logs/{sample}_{resolution}_insulation.log"
    wrapper:
        "master/bio/cooltools/insulation"
