container: "docker://continuumio/miniconda3:4.4.10"


rule run_megahit:
    input:
        reads=["test_reads/sample1_R1.fastq.gz", "test_reads/sample1_R2.fastq.gz"],
    output:
        contigs="assembly/final.contigs.fasta",
    benchmark:
        "logs/benchmarks/assembly/megahit.txt"
    params:
        # all parameters are optional
        extra="--min-count 10 --k-list 21,29,39,59,79,99,119,141",
    log:
        "logs/megahit.log",
    threads: 8
    resources:
        mem_mb=250000,
    wrapper:
        "master/bio/megahit"


rule download_test_reads:
    output:
        ["test_reads/sample1_R1.fastq.gz", "test_reads/sample1_R2.fastq.gz"],
    log:
        "logs/download.log",
    shell:
        "(wget -O - https://zenodo.org/record/3992790/files/test_reads.tar.gz | tar -xzf -) > {log} 2>&1"
