container: "docker://continuumio/miniconda3:4.4.10"


rule run_megahit:
    input:
        reads=["test_reads/sample1_R1.fastq.gz", "test_reads/sample1_R2.fastq.gz"],
    output:
        contigs="assembly/contigs.fasta"
    benchmark:
        "logs/benchmarks/assembly/megahit.txt"
    params:
        # all parameters are optional
        klist="21,29,39,59,79,99,119,141",
        extra="--min-count 10"
    log:
        "logs/megahit.log"
    threads: 8
    resources:
        mem_mb=250000
    wrapper:
        "master/bio/megahit"


rule download_test_reads:
    output:
        ["test_reads/sample1_R1.fastq.gz", "test_reads/sample1_R2.fastq.gz"],
    log:
        "logs/download.log",
    shell:
        " wget https://zenodo.org/record/3992790/files/test_reads.tar.gz >> {log} 2>&1 ; "
        " tar -xzf test_reads.tar.gz >> {log} 2>&1"
