rule microphaser_build:
    input:
        ref_peptides="germline/peptides.fasta",
    output:
        bin="out/peptides.bin",
        peptides="out/peptides.fasta",
    log:
        "logs/microphaser/build_reference.log"
    params:
        extra="--peptide-length 9",  # optional, desired peptide length in amino acids.
    wrapper:
        "master/bio/microphaser/build_reference"
