rule bedtools_merge:
    input:
        "A.bed", # Multiple bed-files can be added as list
    output:
        "A.merged.bed",
    params:
        extra="-c 1 -o count", ## Add optional parameters 
         ## In this example, we want to count how many input lines we merged per output line
    log:
        "logs/merge/A.log",
    wrapper:
        "master/bio/bedtools/merge"
