rule diamond_blastp:
    input: 
        pep = "test.fa",
        db =  "test.dmnd",
    output:
        "test_dmnd.txt.gz"
    params:
        strand="both", # options: both (default), plus, minus
        # optionally increase sensitivity. Default = off
        alignment_sensitivity="sensitive", #options: default, sensitive, more-sensitive
        extra=""
    threads: 4
    wrapper:
        "master/bio/diamond"

rule diamond_blastp_taxonlist:
    input: 
        pep = "test.fa",
        db =  "test.dmnd",
        #Comma-separated list of NCBI taxonomic IDs to filter the database by. Any taxonomic rank can be used, and only reference sequences matching one of the specified taxon ids will be searched against. Using this option requires setting the --taxonmap and --taxonnodes parameters for makedb.
        taxonlist = "taxonlist.txt"
    output:
        "test_dmnd_txlst.txt.gz"
    params:
        strand="both", # options: both (default), plus, minus
        # optionally increase sensitivity. Default = off
        alignment_sensitivity="sensitive", #options: default, sensitive, more-sensitive
        extra=""
    threads: 4
    wrapper:
        "master/bio/diamond"
