rule diamond_blastx:
    input:
        fname_fastq = "reads.fastq",
        fname_db = "database.dmnd"
    output:
        fname = "results.tsv.gz"
    log:
        "logs/diamond_blastx.log"
    params:
        extra="--header --compress 1"
    threads: 8
    wrapper:
        "master/bio/diamond/blastx"
