rule test_sed:
    input:
        "table.csv",
    output:
        "out/sed.csv",
    log:
        "logs/sed.log",
    threads: 1
    params:
        expr="s/ENSG02/ENSG03/",
        extra="",
    wrapper:
        "master/utils/sed"


rule test_sed_regex:
    input:
        "table.csv",
    output:
        "out/sed_regex.csv",
    log:
        "logs/sed_regex.log",
    threads: 1
    params:
        expr=r"s/ENSG0(\d)/ENSG\1/",
        extra="-r",
    wrapper:
        "master/utils/sed"
