# SAMPLE RULE: Custom parameters via extra
rule pytrf_extract:
    input:
        ref="demo_data/{sample}.fasta",  # reference fasta
        repeat="demo_data/{sample}.tsv",  # repeat file from findstr/findgtr/findatr
    output:
        "results/{sample}_extract.tsv",
    params:
        extra="-l 150",  # flank-length=150
    log:
        "logs/{sample}.log",
    wrapper:
        "master/bio/pytrf/extract"
