# SAMPLE RULE: Custom parameters via extra
rule pytrf_extract:
    input:
        "demo_data/{sample}.fasta",  # input[0] - reference fasta
        "demo_data/{sample}.tsv",  # input[1] - repeat file from findstr/findgtr/findatr
    output:
        "results/{sample}_extract.tsv",
    params:
        extra="-l 150",  # flank-length=150
    log:
        "logs/{sample}.log",
    wrapper:
        "master/bio/pytrf/extract"
