rule samtools_fastq:
    input:
        "{prefix}.sam",
    output:
        fq1="{prefix}.1.fasta",
        fq2="{prefix}.2.fasta",
        fq0="{prefix}.0.fasta",
    log:
        "{prefix}.log",
    message:
        ""
    # Samtools takes additional threads through its option -@
    threads: 2  # This value - 1 will be sent to -@
    params:
        outputtype="fasta",
        extra="",
    wrapper:
        "master/bio/samtools/fastx/"
