rule salmon_index:
    input:
        "assembly/transcriptome.fasta",
    output:
        directory("salmon/transcriptome_index"),
    log:
        "logs/salmon/transcriptome_index.log",
    threads: 2
    params:
        extra="", # optional parameters
    wrapper:
        "master/bio/salmon/index"
