rule salmon_index:
    input:
        "assembly/transcriptome.fasta"
    output:
        "salmon/transcriptome_index"
    log:
        "logs/salmon/transcriptome_index.log"
    threads: 2
    params:
        # optional parameters
        extra=""
    wrapper:
        "master/bio/salmon/index"
