rule samtools_index:
    input: "mapped/{sample}.sorted.bam"
    output: "mapped/{sample}.sorted.bam.bai"
    params:
        "" # optional params string
    wrapper:
        "master/bio/samtools/index"
