rule diamond_makedb:
    input: 
        db="pep.fa",
    output: 
        "pep.dmnd"
    params:
        extra=""
    wrapper: 
        "master/bio/diamond/makedb"

## code below enables taxonomy info
import ftputil
from snakemake.remote.FTP import RemoteProvider as FTPRemoteProvider
FTP = FTPRemoteProvider()

rule ftp_get_taxonmap:
    input: FTP.remote(f"ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.gz", static=True, keep_local=True, immediate_close=True)
    output: "prot.accession2taxid.gz"
    shell: "mv {input} {output}"

rule ftp_get_taxonnodes:
    input: FTP.remote(f"ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdmp.zip", static=True, keep_local=True, immediate_close=True)
    output: "nodes.dmp"
    params:
        zipfile= "taxdmp.zip"
    shell:
        """
        mv {input} {params.zipfile}
        unzip {params.zipfile}
        """

rule diamond_makedb_taxinfo:
    input: 
        db="pep.fa",
        taxonmap="prot.accession2taxid.gz",
        taxonnodes="nodes.dmp",
    output: 
        "pep_with_taxinfo.dmnd"
    params:
        extra=""
    wrapper: 
        "master/bio/diamond/makedb"
