rule samtools_view:
    input:
        "{sample}.sam"
    output:
        "{sample}.bam"
    log:
        "{sample}.log"
    params:
        extra="" # optional params string
    wrapper:
        "master/bio/samtools/view"
