name: delly
description: Call variants with delly.
url: https://github.com/dellytools/delly
authors:
  - Johannes Köster
  - Filipe G. Vieira
input:
  - BAM/CRAM file(s)
  - reference genome
  - BED file (optional)
output:
  - VCF/BCF with SVs.
params:
  - command: which command to run [sr/lr]
  - uncompressed_bcf: sets output to uncompressed BCF (ignored if output is `vcf` or `vcf.gz`)
  - extra: additional program arguments
