rule mosdepth:
    input:
        bam = "aligned/{dataset}.bam",
        bai = "aligned/{dataset}.bam.bai",
    output:
        summary = "mosdepth/{dataset}.mosdepth.summary.txt", # this named output is required for prefix parsing
        "mosdepth/{dataset}.mosdepth.global.dist.txt",
        "mosdepth/{dataset}.per-base.bed.gz", # produced unless --no-per-base specified
    log:
        "logs/mosdepth/{dataset}.log"
    params:
        extra = "--fast-mode",  # optional
    threads:  # additional decompression threads through `--threads`
        4     # This value - 1 will be sent to `--threads`
    wrapper: "master/bio/mosdepth"


rule mosdepth_bed:
    input:
        bam = "aligned/{dataset}.bam",
        bai = "aligned/{dataset}.bam.bai",
        bed = "test.bed",
    output:
        summary = "mosdepth/{dataset}.mosdepth.summary.txt", # this named output is required for prefix parsing
        "mosdepth/{dataset}.mosdepth.global.dist.txt",
        "mosdepth/{dataset}.mosdepth.region.dist.txt",
        "mosdepth/{dataset}.regions.bed.gz",
    log:
        "logs/mosdepth_bed/{dataset}.log"
    params:
        extra = "--no-per-base --use-median",  # optional
    threads:  # additional decompression threads through `--threads`
        4     # This value - 1 will be sent to `--threads`
    wrapper: "master/bio/mosdepth"


rule mosdepth_by_threshold:
    input:
        bam = "aligned/{dataset}.bam",
        bai = "aligned/{dataset}.bam.bai",
    output:
        summary = "mosdepth/{dataset}.mosdepth.summary.txt", # this named output is required for prefix parsing
        "mosdepth/{dataset}.mosdepth.global.dist.txt",
        "mosdepth/{dataset}.mosdepth.region.dist.txt",
        "mosdepth/{dataset}.regions.bed.gz",
        "mosdepth/{dataset}.thresholds.bed.gz", # needs to go with params.thresholds spec
    log:
        "logs/mosdepth_by/{dataset}.log"
    params:
        by = "500",  # optional, window size,  specifies --by for mosdepth.region.dist.txt and regions.bed.gz
        thresholds = "1,5,10,30", # optional, specifies --thresholds for thresholds.bed.gz
    threads:  # additional decompression threads through `--threads`
        4     # This value - 1 will be sent to `--threads`
    wrapper: "master/bio/mosdepth"


rule mosdepth_quantize_precision:
    input:
        bam = "aligned/{dataset}.bam",
        bai = "aligned/{dataset}.bam.bai",
    output:
        summary = "mosdepth/{dataset}.mosdepth.summary.txt", # this named output is required for prefix parsing
        "mosdepth/{dataset}.mosdepth.global.dist.txt",
        "mosdepth/{dataset}.quantized.bed.gz", # optional, needs to go with params.quantize spec
    log:
        "logs/mosdepth_quantize_precision/{dataset}.log"
    params:
        extra = "--no-per-base",  # optional
        quantize = "0:1:5:150", # optional, specifies --quantize for quantized.bed.gz
        precision = "5", # optional, set decimals of precision
    threads:  # additional decompression threads through `--threads`
        4     # This value - 1 will be sent to `--threads`
    wrapper: "master/bio/mosdepth"
