rule pretext_graph:
    input:
        bedgraph="{a}.bedgraph",
        map="map.pretext",
    output:
        "{a}.pretext",
    log:
        "logs/{a}.pretext_graph.log",
    params:
        graph_name="graph_name",
        extra="",
    threads: 1
    wrapper:
        "master/bio/pretext/graph"
