rule star_index:
    input:
        fasta="{genome}.fasta",
    output:
        # STAR reference genome index files. Only the common path in the first
        # multiext entry can be chosen arbitrarily. All the filenames are
        # hardcoded into STAR source code, so do not change them.
        multiext(
            "{genome}/",
            "chrLength.txt",
            "chrName.txt",
            "chrNameLength.txt",
            "chrStart.txt",
            "genomeParameters.txt",
            "Genome",
            "SA",
            "SAindex",
        ),
    threads: 1
    params:
        extra="",
    log:
        "logs/star_index_{genome}.log",
    wrapper:
        "master/bio/star/index"
