rule star_index:
    input:
        fasta="{genome}.fasta",
    output:
        multiext(
            "{genome}/",
            "chrLength.txt",
            "chrName.txt",
            "chrNameLength.txt",
            "chrStart.txt",
            "genomeParameters.txt",
            "Genome",
            "SA",
            "SAindex",
        ),
    message:
        "Testing STAR index"
    threads: 1
    params:
        extra="",
    log:
        "logs/star_index_{genome}.log",
    wrapper:
        "master/bio/star/index"
