rule homer_makeTagDir:
    input:
        bam="{sample}.bam", # input bam, can be one or a list of files
    output:
        directory("tagDir/{sample}"),
    params:
        extra="", # optional params, see homer manual
    log:
        "logs/makeTagDir/{sample}.log",
    wrapper:
        "master/bio/homer/makeTagDirectory"
