rule run:
    input:
        ['example_input']
    output:
        ['example_input.tsv']
    params:
        genome='hg38',
        annotators=['biogrid=3.5.171'],
        reports=['text'],
        output_dir='.',
        #args = '-a clinvar -t text'
    wrapper:
        'file:///mnt/d/Git/snakemake-wrappers/bio/open-cravat/wrapper.py'
