rule run:
    input:
        'example_input'
    output:
        ['example_input.xlsx']
    params:
        genome='hg38',
        annotators=['biogrid=3.5.171'],
        reports=['excel'],
        output_dir='.',
    wrapper:
        'master/bio/open-cravat'
