# For *.fa file
rule bismark_genome_preparation_fa:
    input:
         "{genome}/{genome}.fa"
    output:
        directory("{genome}/Bisulfite_Genome")
    params:
        "" # optional params string
    wrapper:
        "master/bio/bismark/bismark_genome_preparation"

# Fo *.fa.gz file:
rule bismark_genome_preparation_fa_gz:
    input:
         "{genome}/{genome}.fa.gz"
    output:
        directory("{genome}/Bisulfite_Genome")
    params:
        "" # optional params string
    wrapper:
        "master/bio/bismark/bismark_genome_preparation"