# For *.fa file
rule bismark_genome_preparation_fa:
    input:
        genome="resources/{genome}/{genome}.fa",
    output:
        bismark_genome_dir=directory("resources/{genome}/bismark/"),
    log:
        "logs/resources/{genome}/bismark_genome_preparation.log",
    params:
        extra="",  # optional params string
    threads: 2  # bismark_genome_preparation requires least 2 threads and at least --cores 2 from workflow run
    wrapper:
        "master/bio/bismark/bismark_genome_preparation"


# For *.fa.gz file:
rule bismark_genome_preparation_fa_gz:
    input:
        genome="resources/{genome}/{genome}.fa.gz",
    output:
        bismark_genome_dir=directory("resources/{genome}/bismark/"),
    log:
        "logs/resources/{genome}/bismark_genome_preparation.log",
    params:
        extra="",  # optional params string
    threads: 2  # bismark_genome_preparation requires least 2 threads and at least --cores 2 from workflow run
    wrapper:
        "master/bio/bismark/bismark_genome_preparation"
