rule multiqc:
    input:
        expand("samtools_stats/{sample}.txt", sample=["a", "b"])
    output:
        "qc/multiqc.html"
    params:
        ""
    log:
        "logs/multiqc.log"
    wrapper:
        "master/bio/multiqc"
