from snakemake.utils import min_version

min_version("9.13.1")

configfile: "config.yaml"

module bwa_mapping:
    meta_wrapper: "master/meta/bio/bwa_mapping"
    config: config

use rule * from bwa_mapping