rule vg_autoindex:  # [hide]
    input:  # [hide]
        ref="{genome}.fasta",  # [hide]
    output:  # [hide]
        multiext("resources/{genome}", ".dist", ".min", ".giraffe.gbz"),  # [hide]
    log:  # [hide]
        "logs/vg_autoindex/{genome}.log",  # [hide]
    params:  # [hide]
        extra="",  # [hide]
    threads: 8  # [hide]
    wrapper:  # [hide]
        "master/bio/vg/autoindex"  # [hide]


rule vg_giraffe:
    input:
        reads=["reads/{sample}.1.fastq", "reads/{sample}.2.fastq"],
        index=multiext("resources/genome", ".dist", ".min", ".giraffe.gbz")
    output:
        "mapped/{sample}.bam",
    log:
        "logs/vg_giraffe/{sample}.log",
    params:
        extra="",
        sorting="none",  # Can be 'none', 'samtools' or 'picard'.
        sort_order="queryname",  # Can be 'queryname' or 'coordinate'.
        sort_extra="",  # Extra args for samtools/picard.
    threads: 8
    wrapper:
        "master/bio/vg/giraffe"
