rule sambamba_flagstat:
    input:
        "mapped/{sample}.bam"
    output:
        "mapped/{sample}.stats.txt"
    params:
        extra=""  # optional parameters
    log:
        "logs/sambamba-flagstat/{sample}.log"
    threads: 1
    wrapper:
        "master/bio/sambamba/flagstat"
