rule run_busco:
    input:
        "transcriptome.fasta"
    output:
        "run_txome_busco/full_table_txome_busco.tsv",
    log:
        "logs/quality/transcriptome_busco.log"
    threads: 8
    params:
        mode="transcriptome",
        lineage_path="metazoa_test",
        # optional parameters
        extra="" 
    wrapper:
        "master/bio/busco"
