rule get_genome:
    output:
        "refs/genome.fasta",
    params:
        species="saccharomyces_cerevisiae",
        datatype="dna",
        build="R64-1-1",
        release="98",
    log:
        "logs/get_genome.log",
    cache: "omit-software"  # save space and time with between workflow caching (see docs)
    wrapper:
        "master/bio/reference/ensembl-sequence"


rule get_single_chromosome:
    output:
        "refs/chr2.fasta",
    params:
        species="saccharomyces_cerevisiae",
        datatype="dna",
        build="R64-1-1",
        release="101",
        chromosome=["II"],  # optional: restrict to one or multiple chromosomes, for multiple see below
    log:
        "logs/get_single_genome.log",
    cache: "omit-software"  # save space and time with between workflow caching (see docs)
    wrapper:
        "master/bio/reference/ensembl-sequence"

rule get_multiple_chromosome:
    output:
        "refs/chr1_and_chr2.fasta",
    params:
        species="saccharomyces_cerevisiae",
        datatype="dna",
        build="R64-1-1",
        release="101",
        chromosome=["I", "II"],  # optional: restrict to one or multiple chromosomes
    log:
        "logs/get_genome.log",
    cache: "omit-software"  # save space and time with between workflow caching (see docs)
    wrapper:
        "master/bio/reference/ensembl-sequence"


rule get_off_branch_genome:
    output:
        "refs/off_branch_genome.fasta",
    params:
        species="bacillus_subtilis_subsp_subtilis_str_168_gca_000009045",
        datatype="dna",
        build="ASM904v1",
        release="59", # note latest release varies with url
        branch="bacteria", # optional for off branch genomes
        url="ftp://ftp.ensemblgenomes.org/pub/", # optional set ftp server source
        collection="bacteria_0_collection", # optional set collection source for genome
    log:
        "logs/get_off_branch_genome.log",
    cache: "omit-software"  # save space and time with between workflow caching (see docs)
    wrapper:
        "master/bio/reference/ensembl-sequence"
