
rule metadmg_lca:
    input:
        aln="{sample}.bam",
        names="names.dmp.gz",
        nodes="nodes.dmp.gz",
        acc2taxid="acc2taxid.tsv",
    output:
        res="results/lca/{sample}.out.gz",
        lca="results/lca/{sample}.lca.gz",
        stats="results/lca/{sample}.tsv",
        log="results/lca/{sample}.log",
    log:
        "logs/lca/{sample}.log",
    params:
        extra="-simscorelow 0.95 -simscorehigh 1.0 -minmapq 30 -howmany 30 -lca_rank genus -fix_ncbi 0",
    threads: 4
    resources:
        mem_mb=1024,
    wrapper:
        "master/bio/metadmg/lca"
