rule bcftools_mpileup:
    input:
        index="genome.fasta.fai",
        ref="genome.fasta", # this can be left out if --no-reference is in options
        alignments="mapped/{sample}.bam",
    output:
        pileup="pileups/{sample}.pileup.bcf",
    params:
        options="--max-depth 100 --min-BQ 15",
    log:
        "logs/bcftools_mpileup/{sample}.log",
    wrapper:
        "master/bio/bcftools/mpileup"
