rule pretext_map:
    input:
        "a.bam",
    output:
        "map.pretext",
    log:
        "logs/pretext_map.log",
    params:
        extra="--sortby length --sortorder descend --mapq 10",
    threads: 1
    wrapper:
        "master/bio/pretext/map"
