rule seqkit_grep_name:
    input:
        fastx="reads/{sample}.fastq",
        patterns="reads/name.txt",
    output:
        fastx="out/grep_name/{sample}.fastq.gz",
    log:
        "logs/grep_name/{sample}.log",
    params:
        extra="--by-name",
    threads: 2
    wrapper:
        "master/bio/seqkit/grep"


rule seqkit_grep_seq:
    input:
        fastx="reads/{sample}.fastq",
        patterns="reads/seq.txt",
    output:
        fastx="out/grep_seq/{sample}.fastq.gz",
    log:
        "logs/grep_seq/{sample}.log",
    params:
        extra="--by-seq",
    threads: 2
    wrapper:
        "master/bio/seqkit/grep"
