rule merge_bams:
    input:
        expand("mapped/{sample}.bam", sample=["a", "b"])
    output:
        "merged.bam"
    log:
        "logs/picard_mergesamfiles.log"
    params:
        extra="VALIDATION_STRINGENCY=LENIENT" # optional: Extra arguments for MergeSamFiles.
    wrapper:
        "master/bio/picard/mergesamfiles"
