rule merge_bams:
    input:
        ["mapped/a.bam", "mapped/b.bam"]
    output:
        "merged.bam"
    log:
        "logs/picard_mergesamfiles.log"
    params:
        extra="VALIDATION_STRINGENCY=LENIENT"
    wrapper:
        "master/bio/picard/mergesamfiles"
