rule test_deseq2_wald_apeglm:
    input:
        dds="dds.RDS",
    output:
        wald_rds="wald_apeglm.RDS",
        wald_tsv="dge_apeglm.tsv",
        deseq2_result_dir=directory("deseq_results_apeglm"),
        normalized_counts_table="counts_apeglm.tsv",
        normalized_counts_rds="counts_apeglm.RDS",
    params:
        deseq_extra="",
        # Optional parameters for `lfcShrink` besides dds, parallel, contrast, and coef
        shrink_extra="type='apeglm'",
        results_extra="",
        contrast=["condition", "A", "B"],
    threads: 1
    log:
        "logs/deseq2_apeglm.log",
    wrapper:
        "master/bio/deseq2/wald"


rule test_deseq2_wald_ashr:
    input:
        dds="dds.RDS",
    output:
        wald_rds="wald_ashr.RDS",
        wald_tsv="dge_ashr.tsv",
        deseq2_result_dir=directory("deseq_results_ashr"),
        normalized_counts_table="counts_ashr.tsv",
        normalized_counts_rds="counts_ashr.RDS",
    params:
        deseq_extra="",
        # Optional parameters for `lfcShrink` besides dds, parallel, contrast, and coef
        shrink_extra="type='ashr'",
        results_extra="",
        contrast=["condition", "A", "B"],
    threads: 1
    log:
        "logs/deseq2_ashr.log",
    wrapper:
        "master/bio/deseq2/wald"


rule test_deseq2_wald_normal:
    input:
        dds="dds.RDS",
    output:
        wald_rds="wald_normal.RDS",
        wald_tsv="dge_normal.tsv",
        deseq2_result_dir=directory("deseq_results_normal"),
        normalized_counts_table="counts_normal.tsv",
        normalized_counts_rds="counts_normal.RDS",
    params:
        deseq_extra="",
        # Optional parameters for `lfcShrink` besides dds, parallel, contrast, and coef
        shrink_extra="type='normal'",
        results_extra="",
        contrast=["condition", "A", "B"],
    threads: 1
    log:
        "logs/deseq2_normal.log",
    wrapper:
        "master/bio/deseq2/wald"

rule test_deseq2_wald_contrast_2_factors:
    input:
        dds="dds.RDS",
    output:
        wald_rds="wald_2f.RDS",
        wald_tsv="dge_2f.tsv",
        deseq2_result_dir=directory("deseq_results_2f"),
        normalized_counts_table="counts_2f.tsv",
        normalized_counts_rds="counts_2f.RDS",
    params:
        deseq_extra="",
        # Optional parameters for `lfcShrink` besides dds, parallel, contrast, and coef
        shrink_extra="type='apeglm'",
        results_extra="",
        contrast=["A", "B"],
    threads: 1
    log:
        "logs/deseq2_2f.log",
    wrapper:
        "master/bio/deseq2/wald"


rule test_deseq2_wald_contrast_1_string:
    input:
        dds="dds.RDS",
    output:
        wald_rds="wald_1s.RDS",
        wald_tsv="dge_1s.tsv",
        deseq2_result_dir=directory("deseq_results_1s"),
        normalized_counts_table="counts_1s.tsv",
        normalized_counts_rds="counts_1s.RDS",
    params:
        deseq_extra="",
        # Optional parameters for `lfcShrink` besides dds, parallel, contrast, and coef
        shrink_extra="type='apeglm'",
        results_extra="",
        contrast=["condition_B_vs_A"],
    threads: 1
    log:
        "logs/deseq2_1s.log",
    wrapper:
        "master/bio/deseq2/wald"
