rule test_deseqdataset_minimal:
    input:
        txi="",
        coldata="",
    output:
        "dds_txi.RDS",
    threads: 1
    log:
        "logs/deseqdataset/txi.log"
    params:
        formula="~Condition",
    wrapper:
        "master/bio/deseq2/DESeqDataSet"


rule test_deseqdataset_txi:
    input:
        txi="",
        coldata="",
    output:
        "dds_txi.RDS",
    threads: 1
    log:
        "logs/deseqdataset/txi.log"
    params:
        formula="~Condition",
        factor="Condition",
        reference_level="Ref",
        tested_level="Test",
        min_counts=0,
        extra="",
    wrapper:
        "master/bio/deseq2/DESeqDataSet"


rule test_deseqdataset_se:
    input:
        se="",
        coldata="",
    output:
        "dds_se.RDS",
    threads: 1
    log:
        "logs/deseqdataset/se.log"
    params:
        formula="~Condition",
        factor="Condition",
        reference_level="Ref",
        tested_level="Test",
        min_counts=0,
        extra="",
    wrapper:
        "master/bio/deseq2/DESeqDataSet"


rule test_deseqdataset_r_matrix:
    input:
        matrix="",
        coldata="",
    output:
        "dds_rmatrix.RDS",
    threads: 1
    log:
        "logs/deseqdataset/r_matrix.log"
    params:
        formula="~Condition",
        factor="Condition",
        reference_level="Ref",
        tested_level="Test",
        min_counts=0,
        extra="",
    wrapper:
        "master/bio/deseq2/DESeqDataSet"


rule test_deseqdataset_tsv_matrix:
    input:
        counts="",
        coldata="",
    output:
        "dds_matrix.RDS",
    threads: 1
    log:
        "logs/deseqdataset/txt_matrix.log"
    params:
        formula="~Condition",
        factor="Condition",
        reference_level="Ref",
        tested_level="Test",
        min_counts=0,
        extra="",
    wrapper:
        "master/bio/deseq2/DESeqDataSet"


rule test_deseqdataset_htseq_dir:
    input:
        htseq_dir="",
        sample_table="",
        coldata="",
    output:
        "dds_htseq.RDS",
    threads: 1
    log:
        "logs/deseqdataset/htseq_dir.log"
    params:
        formula="~Condition",
        factor="Condition",
        reference_level="Ref",
        tested_level="Test",
        min_counts=0,
        extra="",
    wrapper:
        "master/bio/deseq2/DESeqDataSet"
