rule gatk_depth_of_coverage:
    input:
        bam="mapped/a.bam",  # File containing reads
        fasta="genome.fasta",
        intervals="regions.interval_list",  # Regions where the coverage is computed
    output:
        multiext(
            "depth/a",
            "",
            ".sample_interval_summary",
            ".sample_cumulative_coverage_counts",
            ".sample_cumulative_coverage_proportions",
            ".sample_interval_statistics",
            ".sample_statistics",
            ".sample_summary",
        ),
    log:
        "logs/gatk/depthofcoverage.log",
    params:
        extra="",
        java_opts="",
    resources:
        mem_mb=1024,
    wrapper:
        "master/bio/gatk/depthofcoverage"
