rule gatk_depth_of_coverage:
    input:
        bam="mapped/{sample}.bam",  # File containing reads
        fasta="genome.fasta",
        intervals="regions.interval_list",  # Regions where the coverage is computed
    output:
        basename="depths/{sample}",  # File name base for all the output files
    log:
        "logs/gatk/{sample}_depthofcoverage.log",
    params:
        extra="",
        java_opts="",
    resources:
        mem_mb=1024,
    wrapper:
        "master/bio/gatk/depthofcoverage"
