rule bwa_mem2_index:
    input:
        "{genome}"
    output:
        "{genome}.0123",
        "{genome}.amb",
        "{genome}.ann",
        "{genome}.bwt.2bit.64",
        "{genome}.pac",
    log:
        "logs/bwa-mem2_index/{genome}.log"
    params:
        prefix=lambda w: w.genome
    wrapper:
        "master/bio/bwa-mem2/index"
