rule preprocess:
    input:
        vcf="min.vcf",
        csv="min.csv"
    output:
        multiext("plinkdata.", "fam", "map", "ped", "cov")
    params:
        extra_recode="",
        extra_file="",
        missing_code="0",
        phenotype_column_name="binary_column",
        sex_column_name="sex_column",
        sex_male_code="male",
        sex_female_code="female",
        covariables=["quantitative_column", "case_control_with_missingness"]
    log:
        "logs/plink/preprocess.log"
    wrapper:
        "master/bio/plink/preprocess"
