rule mofa2:
    input:
        "{data}.parquet",
    output:
        "{data}.hdf5",
    log:
        "log/{data}.log",
    params:
        scale_groups=False,  # set to TRUE if groups have different ranges/variances
        scale_views=False,  # set to TRUE if views have different ranges/variances
    wrapper:
        "master/bio/mofa2"
