rule debarcer_report:
    input:
        cons="{Sample}/Consfiles/{Region}.cons",
        umis="{Sample}/Umifiles/{Region}.json",
        stats="{Sample}/Stats/",
        data="{Sample}/Datafiles/datafile_{Region}.csv"
    output:
        #figs=directory("{Sample}/Report/Figures/"),
        report="{Sample}/Report/{Region}_debarcer_report.html"
    params:
        sample_report = ""
    log:
        "logs/report/{Sample}_{Region}.log"
    wrapper:
        "debarcer/bio/debarcer/report"