rule samtools_fastq:
    input:
        "{prefix}.sam"
    output:
        "{prefix}.fasta"
    message:
        ""
    threads:  # Samtools takes additional threads through its option -@
        2     # This value - 1 will be sent to -@
    params:
        outputtype = "fasta"
        extra = ""
    wrapper:
        "master/bio/samtools/fastn/"
