rule bcf_to_vcf:
    input:
        bcf="{prefix}.bcf"
    output:
        vcf="{prefix}.vcf"
    params:
        ""  # optional parameters for bcftools view (except -o)
    log:
        "logs/{prefix}.log"
    wrapper:
        "master/bio/bcftools/view"
