rule bcf_to_vcf:
    input:
        bcf="{prefix}.bcf"
    output:
        vcf="{prefix}.vcf"
    params:
        extra=""
    log:
        "logs/{prefix}.log"
    wrapper:
        "master/bio/bcftools/view"
