rule sambamba_merge:
    input:
        ["mapped/{sample}_1.sorted.bam", "mapped/{sample}_2.sorted.bam"]
    output:
        "mapped/{sample}.merged.bam"
    params:
        extra=""  # optional parameters
    threads: 1
    wrapper:
        "master/bio/sambamba/merge"
