rule trim_galore_se:
    input:
        "reads/{sample}.fastq.gz",
    output:
        fasta="trimmed/{sample}_trimmed.fq.gz",
        report="trimmed/report/{sample}.fastq.gz_trimming_report.txt",
    log:
        "logs/trim_galore/{sample}.log",
    params:
        extra="--illumina -q 20",
    wrapper:
        "master/bio/trim_galore/se"


rule trim_galore_se_uncompressed:
    input:
        "reads/{sample}.fastq",
    output:
        fasta="trimmed/{sample}_trimmed.fastq",
        report="trimmed/report/{sample}.fastq_trimming_uncomp_report.txt",
    log:
        "logs/trim_galore/{sample}.uncomp.log",
    params:
        extra="--illumina -q 20",
    threads: 1
    wrapper:
        "master/bio/trim_galore/se"
