rule muscle_fasta:
    input:
        fasta = "{sample}.fa",
    output:
        alignment = "{sample}.afa",
    log:
        "logs/muscle/{sample}.log",
    params:
        extra="",
    threads: 1
    wrapper:
        "master/bio/muscle"

rule muscle_clw:
    input:
        fasta = "{sample}.fa",
    output:
        alignment = "{sample}.clw",
    log:
        "logs/muscle/{sample}.log",
    params:
        extra="-clw",
    threads: 1
    wrapper:
        "master/bio/muscle"
