rule orthanq_candidates_hla:
    input:
        alleles="hla_alleles.fasta",
        genome="genome.fasta",
        xml="hla.xml"
    output:
        "candidates.vcf",
    log:
        "logs/orthanq_candidates/candidates_hla.log",
    wrapper:
        "master/bio/orthanq/hla/candidates"
