
rule metadmg_getdamage:
    input:
        aln="{sample}.bam",
        ref="genome.fasta",
    output:
        res="results/getdamage/{sample}.out.gz",
        dmg="results/getdamage/{sample}.dmg.gz",
        stats="results/getdamage/{sample}.tsv",
    log:
        "logs/getdamage/{sample}.log",
    params:
        extra="-l 30 -p 30 -r 1",
    threads: 4
    resources:
        mem_mb=1024,
    wrapper:
        "master/bio/metadmg/getdamage"
