rule test_unicycler:
    input:
        paired = [
            "reads/reads.R1.fq.gz",
            "reads/reads.R2.fq.gz"
        ]
    output:
        "result/assembly.fasta"
    wrapper:
        "master/bio/unicycler"
