rule qualimap:
    input:
        # BAM aligned, splicing-aware, to reference genome
        bam="mapped/a.bam",
    output:
        report(
            directory("qc/a"),
            htmlindex="qualimapReport.html",
            # see https://snakemake.readthedocs.io/en/stable/snakefiles/reporting.html
            # for more options
        )
    log:
        "logs/qualimap/bamqc/a.log",
    # optional specification of memory usage of the JVM that snakemake will respect with global
    # resource restrictions (https://snakemake.readthedocs.io/en/latest/snakefiles/rules.html#resources)
    # and which can be used to request RAM during cluster job submission as `{resources.mem_mb}`:
    # https://snakemake.readthedocs.io/en/latest/executing/cluster.html#job-properties
    wrapper:
        "master/bio/qualimap/bamqc"
