rule clustalo:
    input:
        "{sample} input.fa"
    output:
        "{sample}.msa.fa"
    log:
        "logs/clustalo/test/{sample}.log"
    params:
        extra=""
    threads: 8
    wrapper:
        "master/bio/clustalo"
