rule clustalo:
    input:
        "{sample} input.fa",
    output:
        "{sample}.msa.fa",
    log:
        "logs/clustalo/test/{sample}.log",
    threads: 8
    params:
        extra="",
    wrapper:
        "master/bio/clustalo"
