rule swarm:
    input:
        "{sample}.fas",
    output:
        structure="out/{sample}.struct.tsv",
        network="out/{sample}.network.tsv",
        output="out/{sample}.clusters",
        statistics="stats/{sample}.stats.tsv",
        uclust="out/{sample}.uclust.tsv",
        seeds="out/{sample}.seeds.fas",
        log="out/{sample}.log",
    log:
        "logs/{sample}.log",
    threads: 4
    params:
        extra="--fastidious --differences 1 --usearch-abundance",
    wrapper:
        "master/bio/swarm"


rule swarm_gz:
    input:
        "{sample}.fas.gz",
    output:
        structure="out/{sample}.gz.struct.tsv",
        network="out/{sample}.gz.network.tsv",
        output="out/{sample}.gz.clusters",
        statistics="stats/{sample}.gz.stats.tsv",
        uclust="out/{sample}.gz.uclust.tsv",
        seeds="out/{sample}.gz.seeds.fas",
        log="out/{sample}.gz.log",
    log:
        "logs/{sample}.gz.log",
    threads: 4
    params:
        extra="--fastidious --boundary 3 --differences 1 --usearch-abundance",
    resources:
        mem_mb=lambda wc, input: input.size_mb * 4 # with the fastidious option, the original swarm 2 paper suggests a factor of 4.75 * input_data (https://peerj.com/articles/1420/#p-22), a later pull request then suggests a 20% reduction in memory usage (https://github.com/torognes/swarm/issues/7#issuecomment-420290892)
    wrapper:
        "master/bio/swarm"


rule swarm_bz2:
    input:
        "{sample}.fas.bz2",
    output:
        structure="out/{sample}.bz2.struct.tsv",
        network="out/{sample}.bz2.network.tsv",
        output="out/{sample}.bz2.clusters",
        statistics="stats/{sample}.bz2.stats.tsv",
        uclust="out/{sample}.bz2.uclust.tsv",
        seeds="out/{sample}.bz2.seeds.fas",
        log="out/{sample}.bz2.log",
    log:
        "logs/{sample}.bz2.log",
    threads: 4
    params:
        extra="--differences 1 --usearch-abundance",
    resources:
        mem_mb=lambda wc, input: input.size_mb * 0.7 # the swarm readme suggests a factor of 0.6 (https://github.com/torognes/swarm/blob/68e0dc095b2bf52ee054c806d72101ea9d2142a9/README.md?plain=1#L103), so this is a conservative memory reservation
    wrapper:
        "master/bio/swarm"
