rule dada2_learn_errors:
    input:
    # Quality filtered and trimmed forward FASTQ files (potentially compressed) 
        fwd=expand("filtered/{sample}.1.fastq", sample=["a","b"]), 
        rev=expand("filtered/{sample}.2.fastq", sample=["a","b"])
    output:
        mfwd="results/dada2/model_fwd.RDS",# save the error model
        mrev="results/dada2/model_rev.RDS",# "
        pfwd="reports/dada2/errors_fwd.png",# plot observed and estimated rates
        prev="reports/dada2/errors_rev.png" # "
    threads: 1 # set desired number of threads here
    wrapper:
        "master/bio/dada2/learn-errors"

