rule seqkit_stats:
    input:
        fastx="reads/{sample}.fastq",
    output:
        stats="out/stats/{sample}.tsv",
    log:
        "logs/stats/{sample}.log",
    params:
        extra="--all --tabular",
    threads: 2
    wrapper:
        "master/bio/seqkit/stats"
