rule gridss_setupreference:
    input:
        reference="reference/genome.fasta",
    output:
        idx=multiext("reference/genome.fasta", ".amb", ".ann", ".bwt", ".dict", ".fai", ".pac", ".sa")
    params:
        extra="--jvmheap 1g"
    log:
        "log/gridss/setupreference.log"
    wrapper:
        "master/bio/gridss/setupreference"