rule gridss_setupreference:
    input:
        reference="reference/genome.fasta",
        dictionary="reference/genome.dict",
        indices=multiext("reference/genome.fasta", ".amb", ".ann", ".bwt", ".pac", ".sa")
    output:
        multiext("reference/genome.fasta", ".gridsscache", ".img")
    log:
        "log/gridss/setupreference.log"
    wrapper:
        "master/bio/gridss/setupreference"