rule seqkit_rmdup_name:
    input:
        fastx="reads/{sample}.fastq",
    output:
        fastx="out/rmdup_name/{sample}.fastq.gz",
        dup_num="out/rmdup_name/{sample}.num.txt",
        dup_seq="out/rmdup_name/{sample}.seq.txt",
    log:
        "logs/rmdup_name/{sample}.log",
    params:
        extra="--by-name",
    threads: 2
    wrapper:
        "master/bio/seqkit/rmdup"


rule seqkit_rmdup_seq:
    input:
        fastx="reads/{sample}.fastq",
    output:
        fastx="out/rmdup_seq/{sample}.fastq.gz",
        dup_num="out/rmdup_seq/{sample}.num.txt",
        dup_seq="out/rmdup_seq/{sample}.seq.txt",
    log:
        "logs/rmdup_seq/{sample}.log",
    params:
        extra="--by-seq",
    threads: 2
    wrapper:
        "master/bio/seqkit/rmdup"
