rule rubic:
    input:
        seg="{samples}/segments.txt",
        markers="{samples}/markers.txt"
#        genefile="path/to/genefile"
    output:
        out_gains="out/{samples}/gains.txt",
        out_losses="out/{samples}/losses.txt",
        out_plots=directory("out/{samples}/plots") #only possible to provide output directory for plots
    log:
        "logs/{samples}/rubic.log"
    params:
        fdr=0.2,
    wrapper:
        "master/bio/rubic"
