rule rubic:
    input:
        seg="{samples}/segments.txt",
        markers="{samples}/markers.txt"
    output:
        out_gains="{samples}/gains.txt",
        out_losses="{samples}/losses.txt",
        out_plots="{samples}/plots"
    params:
        fdr="",
        genefile=""
    wrapper:
        "master/bio/rubic"
