include: "tests.smk"  #[hide]


# SAMPLE RULE 1: Run with params directive that is a must.
# Flags or optional flags should go in extra parameter exactly
# as it would be typed in for a terminal command. In this
# example officially recommended parameters and flag options
# on TRF website are used. Also, use directory function
# to specifiy output folder.
rule run_trf_basic:
    input:
        sample="demo_data/{sample}.fasta",
    output:
        directory("trf_output/{sample}"),
    params:
        match=2,
        mismatch=7,
        delta=7,
        pm=80,
        pi=10,
        minscore=50,
        maxperiod=500,
        extra="-f -d -m",
    wrapper:
        "master/bio/trf"


# SAMPLE RULE 2: Where all params are necessary apart from extra but their
################ order is not strict as in TRF utility. Also missing
################ extra's param can set it to utilities(TRF) default.
rule run_trf_basic_with_change_order_missing_extras:
    input:
        sample="demo_data/{sample}.fasta",
    output:
        directory("trf_output/{sample}"),
    params:
        pm=80,
        pi=10,
        minscore=50,
        maxperiod=500,
        match=2,
        mismatch=7,
        delta=7,
        extra="-l 20",
    wrapper:
        "master/bio/trf"
