rule sambamba_markdup:
    input:
        "mapped/{sample}.bam"
    output:
        "mapped/{sample}.rmdup.bam"
    params:
        extra="-r"  # optional parameters
    threads: 8
    wrapper:
        "master/bio/sambamba/markdup"
