rule replace_rg:
    input:
        "mapped/{sample}.bam"
    output:
        "fixed-rg/{sample}.bam"
    log:
        "logs/picard/replace_rg/{sample}.log"
    params:
        java_options="-Xmx8g",
        extra="RGLB=lib1 RGPL=illumina RGPU={sample} RGSM={sample}"
    wrapper:
        "master/bio/picard/addorreplacereadgroups"
