rule galah_fas:
    input:
        fas=["fas/a.fa", "fas/b.fas.bz2", "fas/c.fasta.gz"],
    output:
        clusters="results.fas.tsv",
        repres="results.fas.list",
    log:
        "logs/out.fas.log",
    params:
        extra="--precluster-ani 0.9 --ani 0.95",
    threads: 2
    resources:
        mem_mb=50,
    wrapper:
        "master/bio/galah"


use rule galah_fas as galah_fas_list with:
    input:
        fas_list="fas/a.fas_list",
    output:
        clusters="results.fas_list.tsv",
        repres="results.fas_list.list",
    log:
        "logs/out.fas_list.log",
