rule bwa_aln:
    input:
        fastq="reads/{sample}.{pair}.fastq",
        # Index can be a list of (all) files created by bwa, or one of them
        index=multiext("genome", ".amb", ".ann", ".bwt", ".pac", ".sa")
    output:
        "sai/{sample}.{pair}.sai"
    params:
        extra=""
    log:
        "logs/bwa_aln/{sample}.{pair}.log"
    threads: 8
    wrapper:
        "master/bio/bwa/aln"
