from snakemake.utils import min_version

min_version("9.13.1")

configfile: "config.yaml"

module bowtie2_sambamba:
    meta_wrapper: "file:../master/meta/bio/bowtie2_sambamba"
    config: config

use rule * from bowtie2_sambamba