rule varlociraptor_alignment_properties:
    input:
        ref="resources/genome.fasta",
        alignments="results/alignments/{sample}.bam",
    output:
        "results/alignment-properties/{sample}.json"
    log:
        "logs/varlociraptor/alignment-properties/{sample}.log"
    wrapper:
        "master/bio/varlociraptor/estimate-alignment-properties"