rule samtools_merge:
    input:
        ["mapped/A.bam", "mapped/B.bam"],
    output:
        "merged.bam",
    params:
        "", # optional additional parameters as string
    threads: 2 # Samtools takes additional threads through its option -@, the value specified here minus 1 will be sent to -@
    wrapper:
        "master/bio/samtools/merge"
