rule samtools_merge:
    input:
        ["mapped/A.bam", "mapped/B.bam"],
    output:
        "merged.bam",
    log:
        "merged.log",
    params:
        extra="",  # optional additional parameters as string
    threads: 8
    wrapper:
        "master/bio/samtools/merge"
