
rule fastqc:
    input:
        "reads/{sample}.fastq"
    output:
        html="qc/{sample}.html",
        zip="qc/{sample}.zip"
    params: ""
    wrapper:
        'file:///Users/Julian/Software/snakemake/snakemake-wrappers/bio/fastqc'
        #"master/bio/fastqc"
