rule varlociraptor_alignment_properties:  # [hide]
    input:  # [hide]
        ref="resources/genome.fasta",  # [hide]
        idx="resources/genome.fasta.fai",  # [hide]
        alignments="results/alignments/{sample}.bam",  # [hide]
    output:  # [hide]
        "results/alignment-properties/{sample}.json",  # [hide]
    log:  # [hide]
        "logs/varlociraptor/alignment-properties/{sample}.log",  # [hide]
    wrapper:  # [hide]
        "master/bio/varlociraptor/estimate-alignment-properties"  # [hide]


rule varlociraptor_preprocess:
    input:
        ref="resources/genome.fasta",
        alignment_properties="results/alignment-properties/{sample}.json",
        alignments="results/alignments/{sample}.bam",
        candidate_variants="results/candidate-variants/{sample}.vcf",  # vcf or bcf supported
    output:
        "results/observations/{sample}.bcf",
    log:
        "logs/varlociraptor/preprocess/{sample}.log",
    params:
        extra="",  # optional additional parameters
    wrapper:
        "master/bio/varlociraptor/preprocess-variants"
