rule snpeff:
    input:
        "{sample}.vcf", # (vcf, bcf, or vcf.gz)
    output:
        calls="snpeff/{sample}.vcf",   # annotated calls (vcf, bcf, or vcf.gz)
        stats="snpeff/{sample}.html",  # summary statistics (in HTML), optional
        csvstats="snpeff/{sample}.csv" # summary statistics in CSV, optional
    log:
        "logs/snpeff/{sample}.log"
    params:
        reference="ebola_zaire", # reference name (from `snpeff databases`)
        extra="-Xmx4g"           # optional parameters (e.g., max memory 4g)
    wrapper:
        "master/bio/snpeff"
