"""Snakemake wrapper for STAR genome"""

__author__ = "Ruiyu Ray Wang"
__copyright__ = "Copyright 2021, Ruiyu Wang"
__email__ = "raywong.chn@gmail.com"
__license__ = "MIT"

from snakemake.shell import shell

## Path to genome index
index = snakemake.input.get("index")

## loadmode = "LoadAndExit" to Load the genome, or
## loadmode = "Remove" to Unload the genome
loadmode = snakemake.params.get("loadmode")

shell(
    """
    STAR --genomeLoad {loadmode} \
         --runThreadN {snakemake.threads} \
         --genomeDir {index} \
         --outSAMmode None \
    rm -f Log.final.out Log.out Log.progress.out SJ.out.tab
    """  # Clear files generated by STAR run
)
