rule tximport:
    input:
        quant = expand("quant/A/quant.sf")
        # Optional transcript/gene links as described in tximport
        # tx2gene = /path/to/tx2gene
    output:
        txi = "txi.RDS"
    message:
        "Testing tximport"
    params:
        type = "salmon",
        txOut = True
    wrapper:
        "master/bio/tximport"
