rule tximport:
    input:
        quant = expand("quant/A/quant.sf")
    output:
        txi = "txi.RDS"
    message:
        "Testing tximport"
    params:
        extra = "type='salmon', txOut=TRUE"
    wrapper:
        "file:.."
