rule homer_findPeaks:
    input:
        tag="tagDir/{sample}", # tagDirectory of sample
         # tagDirectory of control background sample - optional
        control="tagDir/control",
    output:
        "{sample}_peaks.txt",
    params:
        style="histone", # one of 7 basic modes of operation, see homer manual
        extra="", # optional params, see homer manual
    log:
        "logs/findPeaks/{sample}.log",
    wrapper:
        "master/bio/homer/findPeaks"
