rule manta:
    input:
        ref="human_g1k_v37_decoy.small.fasta",
        samples=["mapped/a.bam"],
    output:
        outdir=temp(directory("temp/")),
        vcf="results/diploidSV.vcf.gz",
        tbi="results/diploidSV.vcf.gz.tbi",
        cand_indel_vcf="results/candidateSmallIndels.vcf.gz",
        cand_indel_tbi="results/candidateSmallIndels.vcf.gz.tbi",
        cand_sv_vcf="results/candidateSV.vcf.gz",
        cand_sv_tbi="results/candidateSV.vcf.gz.tbi",
    params:
        extra_cfg="",  # optional
        extra_run="",  # optional
    log:
        "logs/manta.log",
    threads: 2
    resources:
        mem_mb=4096,
    wrapper:
        "master/bio/manta"
