rule bcftools_concat:
    input:
        calls=["a.bcf", "b.bcf"],
    output:
        "all.bcf",
    params:
        "", # optional parameters for bcftools concat (except -o)
    log:
        "logs/bcftools-concat.log"
    wrapper:
        "master/bio/bcftools/concat"
